// Laboratorium. Tiap lab: t=judul, c=skenario, f=input [kunci,label,default,(min,max,step)|'t'],
// d=data contoh [nama,{input},deskripsi], r=langkah hitung [label,rumus,substitusi,hasil], n=catatan.
const q=x=>isFinite(x)?x.toLocaleString('id-ID',{maximumFractionDigits:4}):'tak terdefinisi';
const LB={3:['tvm','amort'],4:['bond','stock'],5:['capm','risk'],6:['ratio'],10:['eoq'],11:['disc'],13:['npv'],14:['risk']};
const L={
tvm:{t:"Nilai waktu dari uang (Bab 3)",c:"Satuan: Rp juta. Ubah input atau pilih data contoh, lalu lihat rumus terisi angkamu.",
f:[["a","Jumlah tunggal",10],["p","Pembayaran anuitas per tahun",2],["i","Bunga per tahun (%)",8],["n","Jumlah tahun",5],["m","Periode majemuk per tahun",4]],
d:[["Dana S2 Rani",{a:10,p:2,i:8,n:5,m:4},"Tabungan 10 juta, tambah 2 juta per tahun, bunga 8%, 5 tahun"],["Cicilan motor",{a:30,p:8,i:12,n:4,m:12},"Harga 30 juta, cicilan 8 juta per tahun, bunga 12%, 4 tahun"]],
r:v=>{const i=Math.max(v.i/100,1e-9),n=v.n,g=(1+i)**n,A=(1-1/g)/i,a=$(v.a),p=$(v.p);return[
["FV jumlah tunggal","FV = PV x (1 + i)^n",`${a} x (1 + ${q(i)})^${n} = ${a} x ${q(g)}`,$(v.a*g)],
["PV jumlah tunggal","PV = FV / (1 + i)^n",`${a} / ${q(g)}`,$(v.a/g)],
["FV anuitas biasa","FVA = PMT x [((1+i)^n - 1) / i]",`${p} x [(${q(g)} - 1) / ${q(i)}]`,$(v.p*(g-1)/i)],
["PV anuitas biasa","PVA = PMT x [(1 - (1+i)^-n) / i]",`${p} x [(1 - ${q(1/g)}) / ${q(i)}]`,$(v.p*A)],
["PV annuity due","PVAD = PVA x (1 + i)",`${$(v.p*A)} x ${q(1+i)}`,$(v.p*A*(1+i))],
["EAR","EAR = (1 + i/m)^m - 1",`(1 + ${q(i)}/${v.m})^${v.m} - 1`,pc((1+i/v.m)**v.m-1)]]},
n:"Anuitas dihitung dengan pembayaran tahunan. Annuity due = pembayaran di awal periode."},
amort:{t:"Amortisasi pinjaman (Bab 3)",c:"Satuan: Rp juta. Cicilan tetap tiap tahun; lihat bagaimana porsi bunga mengecil dan porsi pokok membesar.",
f:[["L","Pokok pinjaman",50],["i","Bunga per tahun (%)",12],["n","Jangka waktu (tahun)",5]],
d:[["Kredit usaha warung",{L:50,i:12,n:5},"Pinjaman 50 juta, bunga 12%, 5 tahun"],["Kredit laptop",{L:15,i:10,n:3},"Pinjaman 15 juta, bunga 10%, 3 tahun"]],
r:v=>{const i=Math.max(v.i/100,1e-9),n=Math.max(1,Math.round(v.n)),A=(1-(1+i)**-n)/i,P=v.L/A;let s=v.L,t='<table class="dt"><tr><th>Tahun</th><th>Cicilan</th><th>Bunga</th><th>Pokok</th><th>Sisa</th></tr>';for(let y=1;y<=n;y++){const b=s*i,k=P-b;s-=k;t+=`<tr><td>${y}</td><td>${$(P)}</td><td>${$(b)}</td><td>${$(k)}</td><td>${$(Math.max(s,0))}</td></tr>`}return[
["Faktor anuitas","PVIFA = (1 - (1+i)^-n) / i",`(1 - (1+${q(i)})^-${n}) / ${q(i)}`,q(A)],
["Cicilan tahunan","PMT = Pinjaman / PVIFA",`${$(v.L)} / ${q(A)}`,$(P)],{h:t+'</table>'}]},
n:"Bunga = sisa pinjaman awal x i. Pokok = cicilan - bunga. Sisa baru = sisa lama - pokok."},
bond:{t:"Harga obligasi vs yield (Bab 4)",c:"Satuan: Rp ribu. Obligasi dengan kupon tahunan; geser yield dan lihat harganya.",
f:[["F","Nilai nominal",1000],["c","Kupon (%)",8,0,15,.5],["y","Yield pasar (%)",8,1,16,.5],["n","Sisa tahun",10,1,30,1]],
d:[["Obligasi A (par)",{F:1000,c:8,y:8,n:10},"Kupon 8%, yield 8%, 10 tahun"],["Obligasi B (yield naik)",{F:1000,c:8,y:11,n:10},"Kupon 8%, yield 11%, 10 tahun"],["Obligasi C (kupon rendah, panjang)",{F:1000,c:3,y:8,n:25},"Kupon 3%, yield 8%, 25 tahun"]],
r:v=>{const pr=y=>{y/=100;return v.F*v.c/100*(1-(1+y)**-v.n)/y+v.F/(1+y)**v.n},y=v.y/100,I=v.F*v.c/100,g=(1+y)**v.n,pk=I*(1-1/g)/y,pp=v.F/g,P=pk+pp,P2=pr(v.y+1);return[
["Bunga kupon per tahun","I = Nominal x kupon",`${$(v.F)} x ${q(v.c/100)}`,$(I)],
["PV kupon","PV = I x [(1 - (1+y)^-n) / y]",`${$(I)} x [(1 - ${q(1/g)}) / ${q(y)}]`,$(pk)],
["PV nominal","PV = Nominal / (1+y)^n",`${$(v.F)} / ${q(g)}`,$(pp)],
["Harga obligasi","P = PV kupon + PV nominal",`${$(pk)} + ${$(pp)}`,$(P)+(P>v.F+.005?" (premium)":P<v.F-.005?" (diskon)":" (par)")],
["Jika yield naik 1 poin","P dihitung ulang dengan y + 1%",`y = ${q(y+.01)}`,$(P2)+" ("+pc(P2/P-1)+")"]]},
n:"Bandingkan Obligasi A dan C: jatuh tempo lebih panjang dan kupon lebih rendah membuat harga lebih sensitif."},
stock:{t:"Saham dengan dividen tumbuh konstan (Bab 4)",c:"Satuan: Rp ribu per lembar saham.",
f:[["d","Dividen tahun depan (D1)",2],["k","Required return ke (%)",12],["g","Pertumbuhan dividen g (%)",4]],
d:[["PT Kopi Senja",{d:2,k:12,g:4},"D1 Rp 2 ribu, ke 12%, g 4%"],["PT Tambang Jaya",{d:5,k:15,g:7},"D1 Rp 5 ribu, ke 15%, g 7%"]],
r:v=>{const k=v.k/100,g=v.g/100;if(k<=g)return[["Catatan","Rumus hanya berlaku jika ke lebih besar dari g","",""]];const V=v.d/(k-g);return[
["Nilai intrinsik","V = D1 / (ke - g)",`${$(v.d)} / (${q(k)} - ${q(g)}) = ${$(v.d)} / ${q(k-g)}`,$(V)],
["Dividend yield","D1 / V",`${$(v.d)} / ${$(V)}`,pc(v.d/V)],
["Capital gains yield","sama dengan g","",pc(g)],
["Total return","Dividend yield + capital gains yield",`${q(v.d/V)} + ${q(g)}`,pc(v.d/V+g)]]},
n:"Total return sama dengan ke, sesuai bahwa harga wajar membuat return harapan = return yang diminta."},
capm:{t:"CAPM dan SML (Bab 5)",c:"Return yang diminta = bunga bebas risiko + premi untuk risiko sistematis.",
f:[["rf","Risk-free rate (%)",4],["rm","Return pasar (%)",10],["b","Beta",1.2,0,2.5,.1]],
d:[["Saham defensif",{rf:4,rm:10,b:.7},"Beta 0,7 (misal perusahaan listrik)"],["Saham sebanding pasar",{rf:4,rm:10,b:1},"Beta 1,0"],["Saham agresif",{rf:4,rm:10,b:1.8},"Beta 1,8 (misal teknologi)"]],
r:v=>{const pm=v.rm-v.rf;return[
["Premi risiko pasar","Rm - Rf",`${$(v.rm)} - ${$(v.rf)}`,$(pm)+"%"],
["Required return","k = Rf + beta x (Rm - Rf)",`${$(v.rf)} + ${$(v.b)} x ${$(pm)}`,$(v.rf+v.b*pm)+"%"],
["Sifat saham","beta di atas 1 agresif, di bawah 1 defensif","beta = "+$(v.b),v.b>1?"Agresif":v.b<1?"Defensif":"Sama dengan pasar"]]},
n:"Titik (beta, k) semuanya berada di garis SML."},
risk:{t:"Risiko: expected return, sigma, CV (Bab 5 dan 14)",c:"Return tiap kondisi ekonomi (%) dan peluangnya (%). Dipakai juga untuk risiko proyek di Bab 14.",
f:[["p1","Peluang resesi (%)",25],["r1","Return saat resesi (%)",-5],["p2","Peluang normal (%)",50],["r2","Return saat normal (%)",10],["p3","Peluang boom (%)",25],["r3","Return saat boom (%)",25]],
d:[["Saham Teknologi A",{p1:25,r1:-5,p2:50,r2:10,p3:25,r3:25},"Return -5%, 10%, 25%"],["Saham Konsumsi B",{p1:25,r1:4,p2:50,r2:8,p3:25,r3:12},"Return 4%, 8%, 12% (lebih stabil)"]],
r:v=>{const P=[v.p1,v.p2,v.p3].map(x=>x/100),R=[v.r1,v.r2,v.r3],E=P.reduce((s,p,j)=>s+p*R[j],0),V=P.reduce((s,p,j)=>s+p*(R[j]-E)**2,0),sd=Math.sqrt(V),T=v.p1+v.p2+v.p3;return[
["Cek peluang","Jumlah peluang harus 100%",$(T)+"%",Math.round(T)==100?"OK":"Belum 100%"],
["Expected return","E(R) = jumlah p x R",P.map((p,j)=>`${q(p)} x ${$(R[j])}`).join(' + '),$(E)+"%"],
["Varians","Var = jumlah p x (R - E)^2",P.map((p,j)=>`${q(p)} x (${$(R[j])} - ${$(E)})^2`).join(' + '),$(V)],
["Standar deviasi","sigma = akar(Var)",`akar(${$(V)})`,$(sd)+"%"],
["Coefficient of variation","CV = sigma / E(R)",`${$(sd)} / ${$(E)}`,$(sd/E)]]},
n:"Bandingkan A dan B: A punya return harapan lebih tinggi, tetapi risiko per unit return (CV) juga lebih besar."},
ratio:{t:"Rasio keuangan dan Du Pont (Bab 6)",c:"Satuan: Rp juta. Isi data laporan keuangan, semua rasio utama terhitung.",
f:[["ca","Aktiva lancar",400],["inv","Persediaan",150],["cl","Utang lancar",200],["ar","Piutang",200],["ta","Total aset",1000],["debt","Total utang",500],["eq","Ekuitas",500],["sales","Penjualan (anggap semua kredit)",2000],["ebit","EBIT",160],["int","Beban bunga",40],["ni","Laba bersih",80]],
d:[["PT Kertas Prima (sehat)",{ca:400,inv:150,cl:200,ar:200,ta:1000,debt:500,eq:500,sales:2000,ebit:160,int:40,ni:80},"Utang sedang, bunga tertutup baik"],["PT Baja Lestari (utang tinggi)",{ca:300,inv:180,cl:250,ar:150,ta:1200,debt:900,eq:300,sales:1500,ebit:100,int:90,ni:20},"Utang besar, bunga hampir tak tertutup"]],
r:v=>{const rt=v.sales/v.ar;return[
["Current ratio","Aktiva lancar / utang lancar",`${$(v.ca)} / ${$(v.cl)}`,$(v.ca/v.cl)+"x"],
["Quick ratio","(Aktiva lancar - persediaan) / utang lancar",`(${$(v.ca)} - ${$(v.inv)}) / ${$(v.cl)}`,$((v.ca-v.inv)/v.cl)+"x"],
["Debt to equity","Total utang / ekuitas",`${$(v.debt)} / ${$(v.eq)}`,$(v.debt/v.eq)+"x"],
["Debt to total assets","Total utang / total aset",`${$(v.debt)} / ${$(v.ta)}`,pc(v.debt/v.ta)],
["Interest coverage","EBIT / beban bunga",`${$(v.ebit)} / ${$(v.int)}`,$(v.ebit/v.int)+"x"],
["Receivable turnover","Penjualan kredit / piutang",`${$(v.sales)} / ${$(v.ar)}`,$(rt)+"x"],
["Rata-rata hari penagihan","365 / receivable turnover",`365 / ${$(rt)}`,$(365/rt)+" hari"],
["Net profit margin","Laba bersih / penjualan",`${$(v.ni)} / ${$(v.sales)}`,pc(v.ni/v.sales)],
["ROA","Laba bersih / total aset",`${$(v.ni)} / ${$(v.ta)}`,pc(v.ni/v.ta)],
["ROE","Laba bersih / ekuitas",`${$(v.ni)} / ${$(v.eq)}`,pc(v.ni/v.eq)],
["Du Pont","ROE = margin x perputaran aset x multiplier ekuitas",`${q(v.ni/v.sales)} x ${q(v.sales/v.ta)} x ${q(v.ta/v.eq)}`,pc(v.ni/v.sales*v.sales/v.ta*v.ta/v.eq)]]},
n:"Rasio hanya bermakna jika dibandingkan dengan tahun lalu dan rata-rata industri. Coba kedua data contoh dan bandingkan."},
npv:{t:"NPV, IRR, PI, dan payback (Bab 13)",c:"Satuan: Rp juta. Dua proyek bersaing dengan investasi sama; lihat apakah semua metode sepakat.",
f:[["o","Investasi awal",10000],["cf","Arus kas per tahun (pisahkan koma)","3000,4000,5000,3000",'t'],["k","Required return (%)",10]],
d:[["Proyek A",{o:10000,cf:"3000,4000,5000,3000",k:10},"Arus kas merata dan cukup panjang"],["Proyek B",{o:10000,cf:"6000,4000,2000,1000",k:10},"Arus kas besar di awal"]],
r:v=>{const cf=v.cf.split(',').map(Number).filter(isFinite),k=v.k/100,f=r=>cf.reduce((s,c,t)=>s+c/(1+r)**(t+1),0)-v.o,pvs=cf.map((c,t)=>c/(1+k)**(t+1)),S=pvs.reduce((a,b)=>a+b,0),np=S-v.o;let lo=-.99,hi=10,ir=NaN;if(f(lo)*f(hi)<=0){for(let j=0;j<100;j++){const m=(lo+hi)/2;f(lo)*f(m)<=0?hi=m:lo=m}ir=(lo+hi)/2}let cum=-v.o,pb="belum kembali dalam umur proyek";for(let t=0;t<cf.length;t++){if(cum+cf[t]>=0){pb=$(t+(-cum)/cf[t])+" tahun";break}cum+=cf[t]}return[
["PV tiap arus kas","CF / (1+k)^t",cf.map((c,t)=>`${$(c)}/${q((1+k)**(t+1))}`).join(' ; '),pvs.map(x=>$(x)).join(' + ')],
["NPV","NPV = jumlah PV - investasi awal",`${$(S)} - ${$(v.o)}`,$(np)+(np>=0?" (terima)":" (tolak)")],
["Profitability index","PI = jumlah PV / investasi awal",`${$(S)} / ${$(v.o)}`,$(S/v.o)],
["IRR","Diskonto yang membuat NPV = 0","dicari numerik (bisection)",pc(ir)+(isFinite(ir)?(ir>=k?" (di atas k, terima)":" (di bawah k, tolak)"):"")],
["Payback","Tahun sampai arus kas kumulatif menutup investasi","",pb]]},
n:"Proyek B balik modal lebih cepat (payback 2 tahun), tetapi NPV-nya lebih kecil dari A. Jadi payback bukan ukuran profitabilitas."},
eoq:{t:"Economic order quantity (Bab 10)",c:"Cari ukuran pesanan yang meminimalkan biaya pesan ditambah biaya simpan.",
f:[["S","Pemakaian per tahun (unit)",10000],["O","Biaya per pesanan (Rp ribu)",50],["C","Biaya simpan per unit per tahun (Rp ribu)",2],["Q","Coba ukuran pesanan",500,100,3000,50]],
d:[["Toko bahan kue",{S:10000,O:50,C:2,Q:500},"10.000 unit/tahun, biaya pesan 50, simpan 2"],["Gudang elektronik",{S:4800,O:120,C:6,Q:300},"4.800 unit/tahun, biaya pesan 120, simpan 6"]],
r:v=>{const e=Math.sqrt(2*v.S*v.O/v.C),tc=x=>v.S/x*v.O+x/2*v.C;return[
["EOQ","EOQ = akar(2 x S x O / C)",`akar(2 x ${$(v.S)} x ${$(v.O)} / ${$(v.C)}) = akar(${$(2*v.S*v.O/v.C)})`,$(e)+" unit"],
["Pesanan per tahun","S / EOQ",`${$(v.S)} / ${$(e)}`,$(v.S/e)],
["Total biaya di EOQ","TC = (S/Q) x O + (Q/2) x C",`(${$(v.S)}/${$(e)}) x ${$(v.O)} + (${$(e)}/2) x ${$(v.C)}`,$(tc(e))],
["Total biaya di Q pilihanmu","TC = (S/Q) x O + (Q/2) x C",`(${$(v.S)}/${$(v.Q)}) x ${$(v.O)} + (${$(v.Q)}/2) x ${$(v.C)}`,$(tc(v.Q))],
["Selisih biaya","TC(Q) - TC(EOQ)","",$(tc(v.Q)-tc(e))]]},
n:"Geser Q: total biaya paling rendah ada di EOQ. Menjauh ke kiri atau kanan membuatnya naik."},
disc:{t:"Biaya tidak mengambil diskon tunai (Bab 11)",c:"Syarat \"2/10 net 30\" berarti diskon 2% jika bayar dalam 10 hari, jatuh tempo hari ke-30.",
f:[["d","Diskon (%)",2,.5,10,.5],["dd","Hari diskon",10,5,30,1],["nt","Hari jatuh tempo (net)",30,15,90,5]],
d:[["Syarat 2/10 net 30",{d:2,dd:10,nt:30},"Diskon 2%, 10 hari, net 30"],["Syarat 1/10 net 60",{d:1,dd:10,nt:60},"Diskon 1%, 10 hari, net 60"]],
r:v=>{const d=v.d/100,c=v.nt>v.dd?d/(1-d)*365/(v.nt-v.dd):NaN;return[
["Biaya tahunan","Biaya = d/(1-d) x 365/(net - hari diskon)",`${q(d)}/${q(1-d)} x 365/(${v.nt} - ${v.dd})`,pc(c)],
["Saran","","",c>.1?"Ambil diskon, walau harus meminjam dulu":"Biaya relatif rendah"]]},
n:"Semakin lama membayar setelah masa diskon, semakin kecil biaya tahunannya."}
};
