const P=["Pengantar","Valuasi","Alat analisis dan perencanaan","Manajemen modal kerja","Penganggaran modal"];
// [no, judul, bagian, ringkasan, poin, rumus, lab]
const C=[
[1,"Peran Manajemen Keuangan",0,"Manajemen keuangan mengurus perolehan, pendanaan, dan pengelolaan aset demi satu tujuan: nilai perusahaan bagi pemiliknya.",["Tiga keputusan inti: investasi, pendanaan, dan manajemen aset.","Tujuan perusahaan adalah memaksimalkan kekayaan pemegang saham (harga saham), bukan sekadar laba.","Agency problem: manajer (agen) bisa punya tujuan berbeda dari pemilik (prinsipal). Solusinya insentif dan pengawasan.","Corporate governance mengatur hubungan pemegang saham, direksi, dan manajemen; ada Sarbanes-Oxley Act 2002.","Treasurer mengurus keputusan keuangan, controller mengurus akuntansi."],[],""],
[2,"Lingkungan Bisnis, Pajak, dan Keuangan",0,"Bentuk usaha, pajak, dan pasar keuangan menentukan ruang gerak keputusan keuangan.",["Empat bentuk usaha: sole proprietorship, partnership, corporation, LLC.","Keunggulan korporasi: tanggung jawab terbatas, kepemilikan mudah dipindah, umur tak terbatas, mudah menghimpun dana besar.","Bunga utang mengurangi pajak, dividen tidak. Itu sebabnya utang punya keuntungan pajak.","Depresiasi dipercepat (MACRS) menurunkan pajak di tahun-tahun awal.","Pasar uang (jangka pendek) vs pasar modal (jangka panjang); pasar primer (baru) vs sekunder (bekas).","Yield dipengaruhi risiko gagal bayar, marketability, jatuh tempo, pajak, dan opsi. Ada juga term structure dan yield curve."],[],""],
[3,"Nilai Waktu dari Uang",1,"Uang hari ini bernilai lebih daripada uang di masa depan. Bab ini adalah fondasi seluruh mata kuliah.",["Gambar time line dulu, baru hitung.","Simple interest hanya dari pokok; compound interest juga dari bunga sebelumnya.","Ordinary annuity: arus kas di akhir periode. Annuity due: di awal periode (nilainya x (1+i)).","Arus kas campuran: hitung satu per satu lalu jumlahkan.","Bandingkan bunga dengan periode majemuk berbeda memakai EAR.","Amortisasi pinjaman: cicilan tetap, porsi pokok makin besar dari waktu ke waktu."],["FV = PV(1+i)^n","PV = FV / (1+i)^n","FV anuitas biasa = PMT x [((1+i)^n - 1) / i]","PV anuitas biasa = PMT x [(1 - (1+i)^-n) / i]","EAR = (1 + i/m)^m - 1"],"tvm"],
[4,"Valuasi Sekuritas Jangka Panjang",1,"Nilai intrinsik sekuritas adalah nilai sekarang arus kas masa depan, didiskonto pada required return.",["Bedakan liquidation, going-concern, book, market, dan intrinsic value.","Obligasi: PV bunga + PV pokok. Zero-coupon hanya PV pokok.","Harga obligasi dan suku bunga bergerak berlawanan.","Jatuh tempo lebih panjang dan kupon lebih rendah membuat harga lebih sensitif.","YTM adalah IRR obligasi.","Saham biasa dinilai dari dividen; hasilnya = dividend yield + capital gains yield."],["Perpetual bond = I / k","Saham preferen V = D / k","Saham tumbuh konstan V = D1 / (ke - g)","Tanpa pertumbuhan V = D1 / ke"],"bond"],
[5,"Risiko dan Return",1,"Return yang diminta investor naik seiring risiko yang tidak bisa dihilangkan.",["Risiko = variabilitas return dari yang diharapkan; diukur dengan standar deviasi.","CV (risiko per unit return) membandingkan investasi berbeda skala.","Risiko portofolio ditentukan terutama oleh kovarians antar-sekuritas.","Risiko sistematis tidak bisa didiversifikasi; risiko tidak sistematis bisa.","Beta = kemiringan characteristic line; SML menggambarkan hubungan return dan beta.","Pasar efisien: bentuk lemah, semi-kuat, kuat."],["E(R) = jumlah p x R","CV = sigma / E(R)","k = Rf + beta x (Rm - Rf)"],"capm"],
[6,"Analisis Laporan Keuangan",2,"Rasio hanya bermakna jika dibandingkan dengan tren dan rata-rata industri.",["Balance sheet = potret satu titik waktu; income statement = satu periode.","Lima kelompok rasio: likuiditas, leverage, coverage, aktivitas, profitabilitas.","Analisis Du Pont memecah ROE.","Pelengkap: trend, common-size, dan index analysis."],["Current ratio = aktiva lancar / utang lancar","Quick ratio = (aktiva lancar - persediaan) / utang lancar","Debt to equity = total utang / ekuitas","Interest coverage = EBIT / beban bunga","Receivable turnover = penjualan kredit / piutang","ROE = margin x perputaran aset x multiplier ekuitas"],""],
[7,"Analisis Dana, Arus Kas, dan Perencanaan",2,"Dari mana dana datang dan ke mana perginya, lalu diproyeksikan ke depan.",["Sumber dana: kas turun, utang/ekuitas naik. Penggunaan: aset naik, utang turun.","Laporan arus kas: operasi, investasi, pendanaan.","Cash budget memproyeksikan penerimaan dan pengeluaran; pertimbangkan rentang kemungkinan.","Pro forma balance sheet dan income statement; sustainable growth rate."],[],""],
[8,"Gambaran Manajemen Modal Kerja",3,"Dua keputusan: berapa aktiva lancar yang dipegang, dan bagaimana membiayainya.",["Net working capital vs gross working capital.","Profitabilitas berbanding terbalik dengan likuiditas.","Profitabilitas bergerak searah dengan risiko.","Modal kerja permanen vs temporer.","Hedging (maturity matching): aset temporer dibiayai utang jangka pendek, aset permanen dengan utang jangka panjang/ekuitas."],["NWC = aktiva lancar - utang lancar"],""],
[9,"Manajemen Kas dan Surat Berharga",3,"Percepat penerimaan, perlambat pembayaran, dan simpan kelebihan kas dengan aman.",["Motif kas: transaksi, spekulasi, berjaga-jaga.","Percepat: lockbox, concentration banking, preauthorized debit.","Perlambat: float, zero balance account, controlled disbursing.","Portofolio surat berharga: ready, controllable, free cash.","Pilih sekuritas berdasar keamanan, marketability, yield, jatuh tempo (T-bills, commercial paper, CD)."],[],""],
[10,"Piutang dan Persediaan",3,"Kebijakan kredit dan persediaan adalah trade-off antara keuntungan dan biaya.",["Kebijakan kredit: standar, jangka waktu, diskon tunai, syarat khusus, penagihan.","Analisis kredit: kumpulkan informasi, analisis, putuskan.","Persediaan: ABC, EOQ, order point, safety stock, JIT."],["EOQ = akar(2 x S x O / C)","S = pemakaian per tahun, O = biaya pesan, C = biaya simpan per unit"],"eoq"],
[11,"Pendanaan Jangka Pendek",3,"Dari trade credit yang spontan sampai pinjaman bank berjaminan.",["Trade credit dan accrued expenses adalah sumber spontan.","Tidak mengambil diskon tunai punya biaya tahunan yang bisa sangat tinggi.","Stretching payables berisiko pada reputasi kredit.","Commercial paper, bankers' acceptance, line of credit, revolving credit.","Compensating balance menaikkan biaya efektif pinjaman."],["Biaya diskon tak diambil = d/(1-d) x 365/(hari bayar - hari diskon)"],"disc"],
[12,"Dasar-Dasar Capital Budgeting",4,"Memilih proyek yang manfaatnya melewati satu tahun, berdasarkan arus kas, bukan laba akuntansi.",["Arus kas inkremental setelah pajak, operasi saja (bukan pembiayaan).","Abaikan sunk cost.","Tiga kelompok arus kas: awal, interim, tahun terakhir (nilai sisa dan modal kerja).","Depresiasi MACRS mempengaruhi pola arus kas lewat penghematan pajak."],[],""],
[13,"Teknik Capital Budgeting",4,"Empat alat menilai proyek; NPV umumnya jadi acuan.",["Payback: mengabaikan nilai waktu dan arus kas setelah payback.","NPV >= 0 terima. IRR >= required return terima. PI >= 1 terima.","IRR ganda bisa muncul pada arus kas nonkonvensional.","Proyek mutually exclusive bisa konflik ranking karena skala, pola arus kas, atau umur.","Capital rationing: urutkan dengan PI. Sensitivity analysis dan post-audit."],["NPV = jumlah CF/(1+k)^t - investasi awal","PI = PV arus masuk / investasi awal","IRR: diskonto yang membuat NPV = 0"],"npv"],
[14,"Risiko dalam Capital Budgeting",4,"Risiko proyek adalah sebaran arus kas; dinilai sendiri dan dalam portofolio perusahaan.",["Ukur dengan standar deviasi dan CV; probability tree atau simulasi.","Peluang NPV < 0 menunjukkan peluang rugi.","Proyek berkorelasi rendah dengan aset lama menurunkan risiko total.","Managerial options: ekspansi, abandon, postpone menambah nilai di atas NPV."],["CV = sigma / nilai harapan"],""]
];
const QS=[
["Tujuan utama perusahaan dalam buku ini adalah...",["Memaksimalkan laba tahun berjalan","Memaksimalkan kekayaan pemegang saham","Meminimalkan pajak","Memaksimalkan pangsa pasar"],1,"Kekayaan pemegang saham tercermin pada harga saham, yang memperhitungkan waktu dan risiko, tidak seperti laba."],
["Arus kas yang terjadi di awal setiap periode disebut...",["Ordinary annuity","Perpetuity","Annuity due","Mixed flow"],2,"Annuity due; nilainya sama dengan ordinary annuity dikali (1+i)."],
["Jika yield pasar naik, harga obligasi yang sudah beredar akan...",["Naik","Turun","Tetap","Tidak bisa ditentukan"],1,"Harga obligasi dan yield bergerak berlawanan."],
["Dividen tahun depan $2, ke = 12%, g = 4%. Nilai saham?",["$16,67","$25","$50","$12,50"],1,"V = 2 / (0,12 - 0,04) = $25."],
["Risiko yang dapat dihilangkan melalui diversifikasi adalah...",["Risiko sistematis","Risiko pasar","Risiko tidak sistematis","Risiko beta"],2,"Risiko tidak sistematis bersifat spesifik perusahaan."],
["Rf = 4%, Rm = 10%, beta = 1,5. Required return menurut CAPM?",["10%","13%","15%","9%"],1,"k = 4% + 1,5 x (10% - 4%) = 13%."],
["Menambah aktiva lancar (ceteris paribus) umumnya...",["Menaikkan likuiditas dan profitabilitas","Menaikkan likuiditas, menurunkan profitabilitas","Menurunkan keduanya","Menurunkan likuiditas, menaikkan profitabilitas"],1,"Profitabilitas berbanding terbalik dengan likuiditas."],
["Biaya tahunan tidak mengambil diskon pada syarat 2/10 net 30?",["2%","18,6%","37,2%","73,5%"],2,"2/98 x 365/20 = sekitar 37,2%."],
["Proyek dengan NPV lebih dari atau sama dengan nol sebaiknya...",["Ditolak","Diterima","Ditunda selalu","Dibandingkan dengan payback saja"],1,"NPV >= 0 berarti proyek memenuhi required return."],
["Dalam capital budgeting, sunk cost sebaiknya...",["Dimasukkan sebagai arus keluar","Diabaikan","Dikurangkan dari NPV","Ditambahkan ke investasi awal"],1,"Sunk cost tidak berubah oleh keputusan, jadi tidak relevan."]
];
const $=x=>isFinite(x)?x.toLocaleString('id-ID',{maximumFractionDigits:2}):'tidak terdefinisi';
const pc=x=>isFinite(x)?$(x*100)+'%':'tidak terdefinisi';
const L={
tvm:{t:"Nilai waktu dari uang (Bab 3)",f:[["a","Jumlah uang (untuk FV/PV tunggal)",1000],["p","Pembayaran anuitas per tahun",100],["i","Bunga per tahun (%)",8],["n","Jumlah tahun",5],["m","Periode majemuk per tahun (untuk EAR)",4]],
r:v=>{const i=Math.max(v.i/100,1e-9),n=v.n,g=(1+i)**n,an=(1-1/g)/i;return[["FV jumlah tunggal",$(v.a*g)],["PV jumlah tunggal",$(v.a/g)],["FV anuitas biasa",$(v.p*(g-1)/i)],["PV anuitas biasa",$(v.p*an)],["PV annuity due",$(v.p*an*(1+i))],["EAR",pc((1+i/v.m)**v.m-1)]]},n:"Anuitas dihitung dengan pembayaran tahunan."},
bond:{t:"Harga obligasi vs yield (Bab 4)",f:[["F","Nilai nominal",1000],["c","Kupon (%)",8,0,15,.5],["y","Yield pasar (%)",8,1,16,.5],["n","Sisa tahun",10,1,30,1]],
r:v=>{const pr=y=>{y/=100;const I=v.F*v.c/100;return I*(1-(1+y)**-v.n)/y+v.F/(1+y)**v.n};const p=pr(v.y),q=pr(v.y+1);return[["Harga obligasi",$(p)],["Status",p>v.F+.005?"Premium":p<v.F-.005?"Diskon":"Par"],["Harga jika yield +1 poin",$(q)],["Perubahan harga",pc(q/p-1)]]},n:"Geser jatuh tempo dan kupon, lalu lihat seberapa sensitif harga terhadap yield. Pembayaran kupon tahunan."},
capm:{t:"CAPM dan SML (Bab 5)",f:[["rf","Risk-free rate (%)",4],["rm","Return pasar (%)",10],["b","Beta",1.2,0,2.5,.1]],
r:v=>[["Premi risiko pasar",$(v.rm-v.rf)+"%"],["Required return",$(v.rf+v.b*(v.rm-v.rf))+"%"],["Sifat saham",v.b>1?"Lebih agresif dari pasar":v.b<1?"Lebih defensif dari pasar":"Sama dengan pasar"]],n:"k = Rf + beta x (Rm - Rf)."},
stock:{t:"Saham tumbuh konstan (Bab 4)",f:[["d","Dividen tahun depan",2],["k","Required return ke (%)",12],["g","Pertumbuhan g (%)",4]],
r:v=>v.k<=v.g?[["Catatan","ke harus lebih besar dari g"]]:[["Nilai intrinsik",$(v.d/((v.k-v.g)/100))]],n:"V = D1 / (ke - g)."},
npv:{t:"NPV, IRR, PI, dan payback (Bab 13)",f:[["o","Investasi awal",10000],["cf","Arus kas per tahun (pisahkan koma)","3000,4000,5000,3000",'t'],["k","Required return (%)",10]],
r:v=>{const cf=v.cf.split(',').map(Number).filter(isFinite),f=(r)=>cf.reduce((s,c,t)=>s+c/(1+r)**(t+1),0)-v.o,np=f(v.k/100);let lo=-.99,hi=10,ir=NaN;if(f(lo)*f(hi)<=0){for(let k=0;k<100;k++){const m=(lo+hi)/2;f(lo)*f(m)<=0?hi=m:lo=m}ir=(lo+hi)/2}let cum=-v.o,pb="belum kembali";for(let t=0;t<cf.length;t++){if(cum+cf[t]>=0){pb=$(t+(-cum)/cf[t])+" tahun";break}cum+=cf[t]}return[["NPV",$(np)],["IRR",pc(ir)],["PI",$((np+v.o)/v.o)],["Payback",pb],["Keputusan NPV",np>=0?"Terima":"Tolak"]]},n:"Arus kas dianggap terjadi di akhir tahun ke-1, ke-2, dan seterusnya."},
eoq:{t:"Economic order quantity (Bab 10)",f:[["S","Pemakaian per tahun (unit)",10000],["O","Biaya per pesanan",50],["C","Biaya simpan per unit per tahun",2],["Q","Coba ukuran pesanan",500,100,3000,50]],
r:v=>{const e=Math.sqrt(2*v.S*v.O/v.C),tc=q=>v.S/q*v.O+q/2*v.C;return[["EOQ (unit)",$(e)],["Pesanan per tahun",$(v.S/e)],["Total biaya pada EOQ",$(tc(e))],["Total biaya pada Q pilihanmu",$(tc(v.Q))],["Selisih",$(tc(v.Q)-tc(e))]]},n:"Geser Q: total biaya paling rendah ada di EOQ."},
disc:{t:"Biaya tidak mengambil diskon tunai (Bab 11)",f:[["d","Diskon (%)",2,.5,10,.5],["dd","Hari diskon",10,5,30,1],["nt","Hari jatuh tempo (net)",30,15,90,5]],
r:v=>{const d=v.d/100,c=v.nt>v.dd?d/(1-d)*365/(v.nt-v.dd):NaN;return[["Biaya tahunan",pc(c)],["Saran",c>.1?"Ambil diskon, walau harus pinjam":"Biaya relatif rendah"]]},n:"Semakin lama membayar setelah masa diskon, semakin kecil biaya tahunannya."}
};
const M=document.getElementById('M');
const done=()=>{try{return JSON.parse(localStorage.getItem('pm-done')||'[]')}catch(e){return[]}};
const save=a=>{try{localStorage.setItem('pm-done',JSON.stringify(a))}catch(e){}};
function mark(n){const d=done(),i=d.indexOf(n);i<0?d.push(n):d.splice(i,1);save(d);render()}
let Q={i:0,s:0,a:null};
function pick(j){Q.a=j;if(j==QS[Q.i][2])Q.s++;render()}
function nextQ(){Q.i++;Q.a=null;render()}
function resetQ(){Q={i:0,s:0,a:null};render()}
const home=()=>{const d=done();let h=`<section class="page"><h2>Selamat datang di perpustakaan</h2><p class="lead">Persiapan UTS Manajemen Keuangan, Bab 1 sampai 14. Ambil satu buku dari rak, baca intinya, lalu coba hitungannya di laboratorium.</p><p class="prog">Sudah dikuasai: <b>${d.length}</b> dari 14 bab. Pita merah di punggung buku menandai bab yang sudah kamu kuasai.</p></section>`;
P.forEach((p,pi)=>{h+=`<div class="shelf"><span class="plate">Bagian ${pi+1}: ${p}</span><div class="books">`+C.filter(c=>c[2]==pi).map(c=>`<a class="spine p${pi}" style="height:${190+(c[0]*37%5)*14}px" href="#/ch/${c[0]}" aria-label="Bab ${c[0]}: ${c[1]}">${d.includes(c[0])?'<i class="rib"></i>':''}<span>${c[0]}. ${c[1]}</span></a>`).join('')+`</div></div>`});return h};
const ch=n=>{const c=C[n-1];if(!c)return home();const d=done().includes(n);return `<section class="page"><p><a href="#/">Kembali ke rak</a></p><h2>Bab ${n}: ${c[1]}</h2><p class="lead">${c[3]}</p><h3>Yang perlu kamu kuasai</h3><ul>${c[4].map(x=>`<li>${x}</li>`).join('')}</ul>${c[5].length?`<h3>Rumus</h3><div class="fm">${c[5].map(x=>`<code>${x}</code>`).join('')}</div>`:''}<p>${c[6]?`<a class="btn" href="#/lab/${c[6]}">Coba di laboratorium</a>`:''}<button class="btn ${d?'on':''}" onclick="mark(${n})">${d?'Sudah dikuasai (klik untuk batal)':'Tandai sudah dikuasai'}</button></p><p>${n>1?`<a href="#/ch/${n-1}">Bab sebelumnya</a> &nbsp; `:''}${n<14?`<a href="#/ch/${n+1}">Bab berikutnya</a>`:''}</p></section>`};
const labs=()=>`<section class="page"><h2>Laboratorium</h2><p class="lead">Ubah angkanya, lihat hasilnya berubah. Cara tercepat memahami rumus.</p><div class="cards">${Object.keys(L).map(k=>`<a href="#/lab/${k}">${L[k].t}</a>`).join('')}</div></section>`;
const lab=k=>{const l=L[k];if(!l)return labs();return `<section class="page"><p><a href="#/lab">Semua laboratorium</a></p><h2>${l.t}</h2><div class="labgrid"><div>${l.f.map(f=>`<label>${f[1]}${f[3]===undefined||f[3]==='t'?'':`: <b id="v_${f[0]}">${f[2]}</b>`}${f[3]==='t'?`<input type="text" value="${f[2]}" data-k="${f[0]}">`:f[3]!==undefined?`<input type="range" min="${f[3]}" max="${f[4]}" step="${f[5]}" value="${f[2]}" data-k="${f[0]}">`:`<input type="number" step="any" value="${f[2]}" data-k="${f[0]}">`}</label>`).join('')}</div><div id="out" aria-live="polite"></div></div><p class="note">${l.n}</p></section>`};
function initLab(k){const calc=()=>{const v={};document.querySelectorAll('[data-k]').forEach(e=>{v[e.dataset.k]=e.type=='text'?e.value:+e.value;const b=document.getElementById('v_'+e.dataset.k);if(b)b.textContent=e.value});document.getElementById('out').innerHTML=L[k].r(v).map(([a,b])=>`<div class="res"><span>${a}</span><strong>${b}</strong></div>`).join('')};document.querySelectorAll('[data-k]').forEach(e=>e.addEventListener('input',calc));calc()}
const cheat=()=>`<section class="page"><h2>Lembar rumus</h2>${C.filter(c=>c[5].length).map(c=>`<h3>Bab ${c[0]}: ${c[1]}</h3><div class="fm">${c[5].map(x=>`<code>${x}</code>`).join('')}</div>`).join('')}</section>`;
const quiz=()=>{if(Q.i>=QS.length)return `<section class="page"><h2>Selesai</h2><p class="lead">Skormu ${Q.s} dari ${QS.length}.</p><p>${Q.s>=8?'Kuat. Lanjutkan ke soal hitungan yang lebih sulit di laboratorium.':'Buka lagi bab yang masih terasa kabur, lalu ulangi latihan ini.'}</p><button class="btn" onclick="resetQ()">Ulangi latihan</button></section>`;const x=QS[Q.i];return `<section class="page"><h2>Soal ${Q.i+1} dari ${QS.length}</h2><p class="lead">${x[0]}</p>${x[1].map((o,j)=>`<button class="opt ${Q.a==null?'':j==x[2]?'ok':j==Q.a?'no':''}" ${Q.a==null?'':'disabled'} onclick="pick(${j})">${o}</button>`).join('')}${Q.a==null?'':`<p class="ex">${x[3]}</p><button class="btn" onclick="nextQ()">Lanjut</button>`}</section>`};
function render(){const [,r,a]=location.hash.slice(1).split('/');let h;if(r=='ch')h=ch(+a);else if(r=='lab')h=a?lab(a):labs();else if(r=='rumus')h=cheat();else if(r=='latihan')h=quiz();else h=home();M.innerHTML=h;if(r=='lab'&&L[a])initLab(a);document.querySelectorAll('nav a').forEach(e=>e.classList.toggle('on',e.dataset.r==(r=='ch'?'':r||'')))}
addEventListener('hashchange',()=>{render();scrollTo(0,0)});render();
