// Latihan UTS: Quiz (teoritis) dan Praktik (hitungan). Dimuat sebelum script.js.
// Topik kisi-kisi: 1 Valuasi, 2 Laporan Keuangan dan Rasio, 3 Cash Flow dan Proyeksi, 4 Risiko dan Return.
// Quiz: [topik, soal, [pilihan], indeks benar, pembahasan, sumber]
// Praktik: fungsi pembangun, angka dihitung lewat kode supaya jawaban dan pembahasan selalu konsisten.
(function(){
const TN=['Semua topik','Valuasi','Laporan Keuangan dan Rasio','Cash Flow dan Proyeksi','Risiko dan Return'];
const TL=['','1. Valuasi','2. Analisis Laporan Keuangan dan Rasio','3. Cash Flow Analysis dan Proyeksi','4. Analisis Risiko dan Return Investasi'];
const fm=(x,d=2)=>isFinite(x)?x.toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d}):'tidak terdefinisi';
const pf=(x,d=2)=>fm(x*100,d)+'%';
const pvifa=(i,n)=>(1-(1+i)**-n)/i;
const avg=a=>a.reduce((s,x)=>s+x,0)/a.length;
const tbl=(head,rows)=>`<div class="tw"><table class="dt"><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</table></div>`;
const W1='Week 2 Valuation (slide)',W2='Week 2 Valuing Long-term Security (slide)',W3='Week 3 Financial Statement Analysis (slide)',W6='Week 6 Fund Analysis, Cash-Flow Analysis, and Financial Planning (Excel)',W7='Week 7 Risk and Managerial Options (slide)',B5='Bab 5 buku Van Horne (Risiko dan Return)';

/* ================= QUIZ (TEORITIS) ================= */
const QZ=[
// ---- 1 Valuasi
[1,'Intrinsic value suatu sekuritas paling tepat didefinisikan sebagai...',['Harga yang tercatat di pasar terbuka saat ini','Nilai sekarang arus kas yang diterima investor, didiskonto pada required return yang sesuai risikonya','Selisih total aset dan total kewajiban di neraca','Uang yang diperoleh jika aset dijual terpisah dari operasinya'],1,'Intrinsic value adalah nilai ekonomis aset: arus kas masa depan didiskonto dengan required return yang mencerminkan risiko. Pilihan A adalah market value, C adalah book value, D adalah liquidation value.',W2+', no. 10-13'],
[1,'Obligasi nominal $1.000, kupon 10%, sisa 9 tahun, required return 12%. Harga obligasi akan...',['Di atas nilai par (premium)','Di bawah nilai par (diskon)','Tepat sama dengan par','Tidak bisa ditentukan tanpa tabel'],1,'Kupon (10%) lebih kecil dari required return (12%), jadi investor hanya mau membayar di bawah par. Hitungannya: 100 x 5,328 + 1.000 x 0,361 = sekitar $893. Kebalikannya: kupon lebih besar dari required return membuat harga di atas par.',W2+', no. 19-22'],
[1,'Dengan PMT, i, dan n yang sama, nilai sekarang annuity due dibanding ordinary annuity adalah...',['Lebih kecil','Sama saja','Lebih besar, dikali faktor (1 + i)','Lebih besar, dikali faktor n'],2,'Arus kas annuity due datang di awal periode, jadi didiskonto satu periode lebih sedikit: PVAD = PVA x (1 + i). Contoh slide: PVA = $2.624,32 sedangkan PVAD = $2.808,02 (x 1,07).',W1+', no. 58-61'],
[1,'Mengapa saham yang tidak membayar dividen tetap bisa bernilai positif, bahkan tinggi?',['Karena dividen memang tidak dipakai dalam valuasi saham','Karena investor berharap menjualnya di harga lebih tinggi (terminal value)','Karena required return saham tanpa dividen sama dengan nol','Karena saham tanpa dividen bebas risiko'],1,'Investor mengandalkan terminal value: harga jual di masa depan yang lebih tinggi dari harga beli. Terminal value itu sendiri bergantung pada ekspektasi pasar pada titik tersebut.',W2+', no. 30'],
[1,'Model dividen tumbuh konstan V = D1 / (ke - g) hanya bermakna jika...',['g lebih besar dari ke','ke lebih besar dari g','g sama dengan nol','D1 sama dengan D0'],1,'Jika g sama dengan atau lebih besar dari ke, nilai saham menjadi tak hingga atau negatif, yang tidak masuk akal. Karena itu model ini mensyaratkan ke > g. Kasus g = 0 adalah model no growth: V = D / ke.',W2+', no. 32'],
[1,'Zero-coupon bond jatuh tempo 10 tahun, nominal $1.000, required return 12%. Nilainya sekitar...',['$1.000','$678','$322','$120'],2,'Obligasi ini tidak membayar kupon, jadi nilainya hanya PV dari pokok: 1.000 / (1,12)^10 = sekitar $322. Jika dibeli $322 dan ditebus $1.000, imbal hasil majemuknya tepat 12% per tahun.',W2+', no. 23-24'],
[1,'Menurut Rule of 72, uang berlipat dua pada bunga majemuk 9% per tahun dalam waktu sekitar...',['4 tahun','8 tahun','12 tahun','16 tahun'],1,'Perkiraan waktu = 72 / bunga (%) = 72 / 9 = 8 tahun (hitungan eksak 8,04 tahun). Slide memberi contoh 12% yang menghasilkan 6 tahun (eksak 6,12).',W1+', no. 33-35'],
[1,'Dengan bunga nominal tahunan yang sama (12%), semakin sering pemajemukan dalam setahun maka...',['Nilai masa depan dan EAR makin besar','Nilai masa depan makin kecil','Tidak ada pengaruh','EAR sama tetapi nilai masa depan berbeda'],0,'Bunga berbunga lebih cepat. Contoh $1.000 selama 2 tahun pada 12%: tahunan $1.254,40; semesteran $1.262,48; kuartalan $1.266,77; bulanan $1.269,73; harian $1.271,20. EAR = (1 + i/m)^m - 1 ikut naik.',W1+', no. 71-77'],
// ---- 2 Rasio
[2,'Quick (acid-test) ratio tidak memasukkan persediaan karena...',['Persediaan bukan aset lancar','Persediaan paling lambat dan paling sulit diubah menjadi kas','Persediaan selalu bernilai nol','Persediaan sudah dihitung di utang lancar'],1,'Quick ratio = (aktiva lancar - persediaan) / utang lancar. Persediaan harus dijual dulu dan sering dijual secara kredit sebelum menjadi kas, sehingga dianggap kurang likuid dibanding kas, surat berharga, dan piutang.',W3+', no. 22-23'],
[2,'Aldine Manufacturing memiliki debt to total assets 45%. Artinya...',['45% ekuitas dibiayai oleh utang','45% aset dibiayai utang dan 55% dibiayai ekuitas pemegang saham','Utang 45% dari penjualan','Utang 45% lebih besar dari ekuitas'],1,'Debt to total assets = total utang / total aset. Hasil 45% berarti sisa 55% pembiayaan berasal dari ekuitas. Semakin tinggi rasio ini, semakin besar risiko keuangan.',W3+', no. 27-28'],
[2,'Receivable turnover Aldine 5,89x, median industri 8,1x. Kesimpulan yang tepat:',['Aldine menagih piutang lebih cepat dari industri','Aldine menagih piutang lebih lambat dari industri','Aldine punya likuiditas pasti lebih baik','Tidak bisa disimpulkan apa pun'],1,'Perputaran lebih rendah berarti jarak penjualan sampai kas diterima lebih panjang. Rata-rata hari penagihan Aldine = 365 / 5,89 = sekitar 62 hari, sedangkan industri 365 / 8,1 = sekitar 45 hari.',W3+', no. 35-37'],
[2,'Net profit margin Aldine di atas median industri, tetapi ROI-nya di bawah median. Penjelasan terbaik berdasarkan Du Pont:',['Total asset turnover Aldine rendah: aset yang dipakai per rupiah penjualan lebih banyak','Margin laba bersih Aldine sebenarnya rendah','Aldine tidak memakai utang sama sekali','Pajak Aldine terlalu tinggi'],0,'ROI = net profit margin x total asset turnover. Jika margin tinggi tetapi ROI rendah, penyebabnya ada di komponen kedua: perputaran total aset rendah, artinya Aldine memakai lebih banyak aset untuk menghasilkan setiap rupiah penjualan.',W3+', no. 52-54'],
[2,'Pada common-size analysis, pos-pos neraca dan laba rugi masing-masing dinyatakan sebagai persentase dari...',['Tahun dasar (base year) = 100%','Total aset (neraca) dan penjualan bersih (laba rugi)','Total ekuitas dan laba bersih','Rata-rata industri'],1,'Common-size: neraca dibagi total aset, laba rugi dibagi penjualan. Index analysis berbeda: tahun dasar dijadikan 100 dan tahun lain dinyatakan relatif terhadapnya.',W3+', no. 60-65'],
[2,'Jika perusahaan memperpanjang masa pembayaran ke pemasok (payable days naik) dengan hal lain tetap, maka cash cycle akan...',['Memanjang','Memendek','Tidak berubah','Menjadi nol otomatis'],1,'Cash cycle = operating cycle - payable days (atau hari piutang + hari persediaan - hari utang usaha). Semakin lama membayar pemasok, semakin pendek waktu dana perusahaan tertahan.',W3+', no. 42-43'],
[2,'EBIT perusahaan $300 dan beban bunga $60. Median industri interest coverage 4,0x. Kesimpulannya:',['Coverage 5,0x, di atas median, margin keamanan baik','Coverage 0,2x, berbahaya','Coverage 5,0x, di bawah median','Coverage 240x'],0,'Interest coverage = EBIT / beban bunga = 300 / 60 = 5,0x. Lebih tinggi dari median 4,0x, artinya kemampuan menutup bunga lebih baik dari rata-rata industri.',W3+', no. 31-33'],
[2,'Inventory turnover yang sangat tinggi dapat berarti...',['Manajemen persediaan pasti buruk','Efisien, tetapi bisa juga stok terlalu tipis sehingga sering kehabisan barang (stockout)','Persediaan menumpuk','Piutang tidak tertagih'],1,'Perputaran tinggi umumnya tanda efisiensi, tetapi slide mengingatkan bahwa nilai ekstrem bisa menandakan stok kurang sehingga penjualan hilang. Sebaliknya perputaran rendah (Aldine 2,02x vs industri 3,3x) menandakan stok berlebih.',W3+', no. 39-40'],
// ---- 3 Cash flow & proyeksi
[3,'Dalam analisis sources and uses of funds, mana yang termasuk SUMBER dana?',['Kenaikan persediaan','Penurunan piutang usaha','Penurunan utang jangka panjang','Kenaikan kas'],1,'Aturan: aset turun = sumber, aset naik = penggunaan; kewajiban atau ekuitas naik = sumber, kewajiban atau ekuitas turun = penggunaan. Piutang turun berarti kas masuk dari penagihan, jadi sumber.',W6+', sheet Q1'],
[3,'Pada PT Andika Prima, kas naik Rp10 dan utang usaha turun Rp10. Keduanya diklasifikasikan sebagai...',['Sumber dana','Penggunaan dana','Kas naik sumber, utang usaha turun penggunaan','Kas naik penggunaan, utang usaha turun sumber'],1,'Kas (aset) naik = penggunaan dana, sebab dana ditahan sebagai kas. Utang usaha (kewajiban) turun = penggunaan dana, sebab dana dipakai untuk melunasi. Jadi keduanya penggunaan.',W6+', sheet Answer of Q1'],
[3,'Total sumber dana PT Andika Prima Rp206. Total penggunaan dana seharusnya...',['Rp206, karena neraca harus seimbang','Rp261, karena subtotal aktiva lancar ikut dijumlah','Selalu lebih besar dari sumber','Rp0'],0,'Perubahan aset harus sama dengan perubahan kewajiban dan ekuitas, jadi total sumber = total penggunaan = Rp206. Angka 261 di tabel jawaban muncul karena subtotal aktiva lancar (55) ikut dijumlah, padahal itu hasil penjumlahan item-item di bawahnya.',W6+', sheet Answer of Q1'],
[3,'Pembelian mesin pabrik dicatat pada laporan arus kas di aktivitas...',['Operasi','Investasi','Pendanaan','Tidak dicatat'],1,'Tiga aktivitas: operasi (inti bisnis), investasi (beli atau jual aset), pendanaan (utang dan ekuitas). Pembelian mesin = investasi. Penerbitan saham dan pelunasan utang bank = pendanaan.',W3+', no. 11-12'],
[3,'Dalam proyeksi laporan keuangan, piutang usaha tahun depan umumnya diproyeksikan dengan...',['Penjualan proyeksi x DSO / 365','HPP proyeksi x DSO / 365','Total aset x DSO','Laba bersih x DSO / 365'],0,'DSO (days sales outstanding) = piutang / penjualan x 365, jadi piutang = penjualan x DSO / 365. Piutang bergantung pada penjualan kredit, bukan HPP.',W6+', sheet Answer of Q3'],
[3,'Persediaan dan utang usaha diproyeksikan berdasarkan...',['Penjualan','HPP (COGS), memakai DIO dan DPO','Total aset','Beban bunga'],1,'Persediaan dan utang usaha dibeli atau dibayar sesuai biaya barang, bukan harga jual. Karena itu DIO = persediaan / HPP x 365 dan DPO = utang usaha / HPP x 365. Proyeksinya: HPP proyeksi x DIO atau DPO / 365.',W6+', sheet Answer of Q3'],
[3,'Penjualan: 2021 Rp200, 2022 Rp220, 2023 Rp242. Dengan rata-rata pertumbuhan historis, proyeksi 2024 adalah...',['Rp264,0','Rp266,2','Rp242,0','Rp300,0'],1,'Pertumbuhan 2022 = 10%, 2023 = 10%, rata-rata 10%. Proyeksi 2024 = 242 x 1,10 = Rp266,2.',W6+', sheet Answer of Q2'],
[3,'Metode proyeksi COGS pada contoh PT Sejahtera Abadi memakai...',['Rata-rata rasio HPP terhadap penjualan 3 tahun terakhir','Pertumbuhan HPP tahun lalu saja','HPP tetap sama dengan tahun lalu','Rata-rata SG&A'],0,'COGS = rasio rata-rata HPP/penjualan x penjualan proyeksi. Rasio historis: 75,0%, 73,6%, 72,5%, rata-rata 73,7%.',W6+', sheet Answer of Q2'],
// ---- 4 Risiko & return
[4,'Menurut materi Risk in Capital Budgeting, risiko proyek paling tepat dimaknai sebagai...',['Kemungkinan perusahaan bangkrut','Variabilitas arus kas dari yang diharapkan','Besarnya investasi awal','Lamanya payback'],1,'Risiko investasi adalah sebaran (dispersi) arus kas aktual terhadap yang diharapkan. Semakin besar dispersi, semakin besar risiko. Ukuran utamanya: standar deviasi.',W7+', no. 3-5'],
[4,'Proposal A dan B sama-sama expected value $4.000. Standar deviasi A $548, B $1.095. Kesimpulan:',['A lebih berisiko','B lebih berisiko; CV B lebih besar dari CV A','Risiko sama karena expected value sama','Tidak bisa dibandingkan'],1,'Dengan expected value sama, standar deviasi lebih besar berarti lebih berisiko. CV A = 548/4.000 = 0,14; CV B = 1.095/4.000 = 0,27. Investor yang menghindari risiko memilih A.',W7+', no. 7-8'],
[4,'Coefficient of variation (CV) berguna karena...',['Mengukur risiko per unit expected value, sehingga bisa membandingkan investasi dengan skala berbeda','Selalu sama dengan standar deviasi','Menghitung peluang rugi','Menggantikan NPV'],0,'CV = sigma / expected value, ukuran risiko relatif. Standar deviasi saja menyesatkan jika expected value berbeda jauh. Contoh lab: Saham A (E 10%, sigma 10,6%) CV 1,06 versus Saham B (E 8%, sigma 2,8%) CV 0,35.',W7+', no. 8'],
[4,'Pada distribusi normal, kira-kira berapa persen peluang hasil jatuh dalam +/- 1 standar deviasi dari expected value?',['50%','68%','95%','99%'],1,'Aturan normal: sekitar 68% dalam 1 sigma, 95% dalam 2 sigma, lebih dari 99% dalam 3 sigma. Jadi hanya sekitar 32% peluang hasil melenceng lebih dari 1 sigma.',W7+', no. 6'],
[4,'Pada probability tree, arus kas didiskonto memakai risk-free rate. Alasannya...',['Karena proyek tidak punya risiko','Risiko sudah dianalisis terpisah lewat sebaran NPV; memasukkan premi risiko ke diskonto menghitung risiko dua kali','Karena risk-free rate paling tinggi','Karena pajak'],1,'Tujuan diskonto di tahap ini hanya mengisolasi nilai waktu uang. Risiko dinilai dari standar deviasi NPV. Menambah premi risiko di tingkat diskonto akan double counting.',W7+', no. 12'],
[4,'Perusahaan mempertimbangkan proyek baru yang berkorelasi rendah atau negatif dengan aset yang ada. Dampak ke risiko total perusahaan:',['Risiko total naik pasti','Risiko total bisa turun (diversifikasi)','Tidak ada pengaruh','Expected NPV hilang'],1,'Standar deviasi portofolio proyek bukan penjumlahan sigma; korelasi rendah memperkecilnya. Contoh slide: CV perusahaan turun dari 1,17 menjadi 0,86 setelah menambah proyek 2.',W7+', no. 16-20'],
[4,'Risiko yang dapat dikurangi lewat diversifikasi dan tidak dikompensasi dalam CAPM adalah...',['Risiko sistematis','Risiko tidak sistematis (spesifik perusahaan)','Risiko pasar','Risiko beta'],1,'Risiko tidak sistematis (unik perusahaan) bisa dihilangkan dengan diversifikasi, sehingga pasar tidak membayar premi untuknya. Yang dihargai CAPM hanya risiko sistematis yang diukur beta.',B5],
[4,'Saham dengan beta 1,5 menurut CAPM...',['Defensif; required return di bawah pasar','Agresif; cenderung bergerak 1,5 kali pasar dan required return di atas return pasar','Sama dengan pasar','Bebas risiko'],1,'Beta di atas 1 = agresif. k = Rf + beta x (Rm - Rf), jadi premi risikonya 1,5 kali premi pasar. Beta di bawah 1 = defensif.',B5]
];

/* ================= PRAKTIK (HITUNGAN) ================= */
// Format hasil: {t,h,q,a,pre,u,d,steps,cara,jebak,s}. steps: [label,rumus,substitusi,hasil] atau {h:html}
const PB=[
// ================== 1. VALUASI
()=>{const P=1000,i=.12,m=4,n=2,f=P*(1+i/m)**(m*n);return{t:1,h:'FV dengan pemajemukan kuartalan',q:'Julie Miller menyimpan <b>$1.000</b> selama <b>2 tahun</b> pada bunga nominal <b>12% per tahun</b>, dimajemukkan <b>per kuartal</b>. Berapa nilai akhirnya?',a:f,pre:'$',
steps:[['Samakan periode','i per periode = i / m ; jumlah periode = n x m',`i = 12% / 4 = 3% ; periode = 2 x 4 = 8`,''],['Faktor majemuk','(1 + i/m)^(m x n)',`(1,03)^8`,fm(1.03**8,4)],['FV','FV = PV x (1 + i/m)^(m x n)',`1.000 x ${fm(1.03**8,4)}`,'$'+fm(f)]],
cara:['Baca soal: ada uang sekarang dan ditanya nilai di masa depan, jadi ini soal FV.','Cek frekuensi pemajemukan. Kata "per kuartal" berarti m = 4.','Bagi bunga tahunan dengan m, kalikan jumlah tahun dengan m.','Pangkatkan (1 + i/m) dengan jumlah periode, lalu kalikan dengan PV.','Cek kewajaran: hasil harus sedikit di atas FV tahunan ($1.254,40) karena bunga berbunga lebih sering.'],
jebak:'Kesalahan paling umum: memakai 12% dan 2 periode langsung (hasil $1.254,40) atau lupa membagi bunga dengan m.',s:W1+', no. 71-75'}},
()=>{const cf=[600,600,400,400,100],i=.10,pv=cf.map((c,t)=>c/(1+i)**(t+1)),S=pv.reduce((a,b)=>a+b,0);return{t:1,h:'PV arus kas campuran',q:'Julie Miller akan menerima arus kas akhir tahun 1 sampai 5 berturut-turut: <b>$600, $600, $400, $400, $100</b>. Berapa nilai sekarangnya pada diskonto <b>10%</b>?',a:S,pre:'$',
steps:[...cf.map((c,t)=>[`PV tahun ${t+1}`,'PV = CF / (1 + i)^t',`${c} / (1,10)^${t+1} = ${c} / ${fm(1.1**(t+1),4)}`,'$'+fm(pv[t])]),['Jumlahkan semua','PV total = jumlah PV tiap tahun','545,45 + 495,87 + 300,53 + 273,21 + 62,09','$'+fm(S)]],
cara:['Gambar time line dan tulis tiap arus kas di tahunnya.','Karena nilainya tidak sama semua, gunakan cara "satu per satu" (piece-at-a-time).','Diskontokan tiap arus kas: CF dibagi (1 + i) pangkat tahunnya.','Jumlahkan semua PV.','Alternatif lebih cepat: kelompokkan sebagai anuitas ($600 x 2 tahun, $400 x 2 tahun yang ditunda 2 tahun) ditambah single cash flow $100.'],
jebak:'Jangan menjumlah arus kas dulu baru didiskonto; setiap arus kas punya waktu berbeda. Selisih kecil dengan tabel (1.677,27) hanya karena pembulatan faktor.',s:W1+', no. 63-70'}},
()=>{const P=1000,i=.06,n=3,pm=P*i/(1-(1+i)**-n);let s=P,rows=[];for(let y=1;y<=n;y++){const b=s*i,k=pm-b;rows.push([y,fm(s),fm(pm),fm(b),fm(k),fm(s-k)]);s-=k}const b2=(P-(pm-P*i))*i;return{t:1,h:'Amortisasi pinjaman: bunga tahun ke-2',q:'Tn. Harry Potter meminjam <b>$1.000</b> dari bank selama <b>3 tahun</b> dengan bunga <b>6% per tahun</b>, dibayar cicilan tetap setiap akhir tahun. Berapa <b>porsi bunga pada cicilan tahun ke-2</b>?',a:b2,pre:'$',
steps:[['Hitung cicilan tetap','PMT = PVA x i / (1 - (1+i)^-n)',`1.000 x 0,06 / (1 - 1,06^-3) = 60 / ${fm(1-1.06**-3,6)}`,'$'+fm(pm)],['Bunga tahun 1','Bunga = saldo awal x i',`1.000 x 0,06`,'$60,00'],['Pokok tahun 1 dan saldo akhir','Pokok = PMT - bunga ; saldo akhir = saldo awal - pokok',`${fm(pm)} - 60 = ${fm(pm-60)} ; saldo = ${fm(P-(pm-60))}`,''],['Bunga tahun 2','Bunga = saldo awal tahun 2 x i',`${fm(P-(pm-60))} x 0,06`,'$'+fm(b2)],{h:'<p class="note">Skedul amortisasi lengkap:</p>'+tbl(['Tahun','Saldo awal','Cicilan','Bunga','Pokok','Saldo akhir'],rows)}],
cara:['Anggap pinjaman sebagai PV dari anuitas; cari dulu cicilan PMT.','Buat tabel: saldo awal, cicilan, bunga, pokok, saldo akhir.','Bunga tiap tahun = saldo awal tahun itu x i.','Pokok = cicilan - bunga. Saldo akhir = saldo awal - pokok.','Ulangi untuk tahun berikutnya sampai saldo akhir nol. Total pokok harus sama dengan pinjaman.'],
jebak:'Bunga dihitung dari saldo awal yang terus mengecil, bukan dari pinjaman awal. Karena itu porsi bunga turun dan porsi pokok naik setiap tahun.',s:W1+', no. 95-99'}},
()=>{const I=100,k=.12,n=9,F=1000,V=I*pvifa(k,n)+F/(1+k)**n;return{t:1,h:'Harga obligasi kupon tahunan',q:'Obligasi nominal <b>$1.000</b>, kupon <b>10%</b> (dibayar tahunan), sisa <b>9 tahun</b>. Required return investor <b>12%</b>. Berapa nilai obligasinya?',a:V,pre:'$',
steps:[['Kupon tahunan','I = nominal x kupon',`1.000 x 10%`,'$100'],['PV kupon (anuitas)','I x [(1 - (1+k)^-n) / k]',`100 x ${fm(pvifa(k,n),4)}`,'$'+fm(I*pvifa(k,n))],['PV nominal (single)','F / (1+k)^n',`1.000 / ${fm(1.12**9,4)}`,'$'+fm(F/(1+k)**n)],['Nilai obligasi','V = PV kupon + PV nominal',`${fm(I*pvifa(k,n))} + ${fm(F/(1+k)**n)}`,'$'+fm(V)+' (di bawah par karena kupon < required return)']],
cara:['Pisahkan arus kas obligasi menjadi dua: kupon (anuitas) dan pokok (satu kali di akhir).','Hitung kupon tahunan = nominal x tingkat kupon.','Diskontokan kupon dengan faktor PVIFA pada required return, bukan pada tingkat kupon.','Diskontokan nominal dengan faktor PVIF.','Jumlahkan. Cek logika: kupon < required return berarti harga harus di bawah par.'],
jebak:'Diskonto memakai required return (12%), bukan kupon (10%). Kupon hanya menentukan besarnya arus kas.',s:W2+', no. 18-22'}},
()=>{const I=50,r=.07,n=24,F=1000,V=I*pvifa(r,n)+F/(1+r)**n;return{t:1,h:'Obligasi kupon semesteran',q:'Obligasi US Blivet: kupon <b>10%</b> dibayar <b>dua kali setahun</b>, nominal <b>$1.000</b>, sisa <b>12 tahun</b>, nominal annual required return <b>14%</b>. Berapa nilainya?',a:V,pre:'$',
steps:[['Ubah ke basis semesteran','kupon = I/2 ; periode = 2n ; diskonto = kd/2',`kupon = 100/2 = 50 ; periode = 24 ; diskonto = 14%/2 = 7%`,''],['PV kupon','50 x PVIFA(7%, 24)',`50 x ${fm(pvifa(r,n),4)}`,'$'+fm(I*pvifa(r,n))],['PV nominal','1.000 / (1,07)^24',`1.000 / ${fm(1.07**24,4)}`,'$'+fm(F/(1+r)**n)],['Nilai obligasi','V = PV kupon + PV nominal',`${fm(I*pvifa(r,n))} + ${fm(F/(1+r)**n)}`,'$'+fm(V)]],
cara:['Lihat frekuensi kupon: dua kali setahun berarti m = 2.','Kupon per periode = kupon tahunan / 2. Jumlah periode = tahun x 2. Diskonto per periode = required return / 2.','Hitung seperti obligasi biasa, tetapi dengan angka per semester.','Hasil tetap dalam dolar, tidak perlu dikonversi lagi.'],
jebak:'Semua tiga angka (kupon, periode, diskonto) harus disesuaikan. Menyesuaikan satu atau dua saja akan menghasilkan nilai yang salah.',s:W2+', no. 25-26'}},
()=>{const D=9,kp=.14,V=D/kp;return{t:1,h:'Nilai saham preferen',q:'Margana Cipher Corp. memiliki saham preferen <b>9%, nilai par $100</b>. Required return investor <b>14%</b>. Berapa nilai saham preferen tersebut?',a:V,pre:'$',
steps:[['Dividen tahunan','Dp = par x tingkat dividen',`100 x 9%`,'$9'],['Nilai (perpetuitas)','V = Dp / kp',`9 / 0,14`,'$'+fm(V)]],
cara:['Saham preferen membayar dividen tetap tanpa jatuh tempo, mirip perpetual bond.','Hitung dividen dalam dolar: par x persentase dividen.','Bagi dengan required return: V = Dp / kp.'],
jebak:'Dp adalah dividen dalam dolar ($9), bukan persentasenya (9%).',s:W2+', no. 28'}},
()=>{const D1=4,g=.06,k=.14,V=D1/(k-g);return{t:1,h:'Saham dengan dividen tumbuh konstan',q:'Dividen LKN, Inc. tahun depan (D1) diperkirakan <b>$4</b>, tumbuh <b>6% selamanya</b>, required return <b>14%</b>. Berapa nilai saham?',a:V,pre:'$',
steps:[['Cek syarat','ke harus lebih besar dari g','14% > 6% (memenuhi)',''],['Nilai saham','V = D1 / (ke - g)',`4 / (0,14 - 0,06) = 4 / 0,08`,'$'+fm(V)]],
cara:['Periksa dulu: dividen yang diberikan D1 (tahun depan) atau D0 (sekarang)?','Jika D0, ubah dulu: D1 = D0 x (1 + g).','Pastikan ke > g.','Bagi D1 dengan (ke - g).'],
jebak:'Kalau soal memberi D0, jangan langsung dibagi. Kalikan (1 + g) dulu untuk mendapat D1.',s:W2+', no. 32-33'}},
()=>{const b=.4,k=.14,g=.06,E1=6.67,m=(1-b)/(k-g);return{t:1,h:'Earnings multiplier (P/E)',q:'LKN, Inc. menahan <b>40%</b> laba (retention), ke = <b>14%</b>, g = <b>6%</b>. Berapa <b>earnings multiplier</b> tertinggi (kali) yang bersedia dibayar investor? (Laba per saham tahun depan $6,67.)',a:m,u:'x',
steps:[['Payout ratio','payout = 1 - retention',`1 - 0,40`,'0,60'],['Earnings multiplier','P/E = payout / (ke - g)',`0,60 / (0,14 - 0,06) = 0,60 / 0,08`,fm(m)+'x'],['Cek nilai saham','V = E1 x P/E',`6,67 x 7,5`,'$'+fm(E1*m)+' (sama dengan model dividen: $50)']],
cara:['Konversi model dividen: D1 = E1 x payout.','Payout = 1 - retention rate.','V = E1 x payout / (ke - g), sehingga multiplier = payout / (ke - g).','Untuk mendapat harga, kalikan multiplier dengan EPS tahun depan.'],
jebak:'Yang dipakai payout (bagian laba yang dibayar), bukan retention. Salah memakai 0,40 menghasilkan 5x.',s:W2+', no. 34-35'}},
()=>{const D0=2,k=.14,g1=.10,g2=.06,D=[1,2,3,4,5].map(t=>D0*(1+g1)**t),pvd=D.map((d,t)=>d/(1+k)**(t+1)),D6=D[4]*(1+g2),P5=D6/(k-g2),pP=P5/(1+k)**5,V=pvd.reduce((a,b)=>a+b,0)+pP;return{t:1,h:'Saham dengan dua fase pertumbuhan',q:'Dividen sekarang (D0) <b>$2</b>. Dividen tumbuh <b>10% per tahun selama 5 tahun</b>, setelah itu tumbuh <b>6% selamanya</b>. Required return <b>14%</b>. Berapa nilai saham?',a:V,pre:'$',
steps:[...D.map((d,t)=>[`D${t+1} dan PV-nya`,`D${t+1} = 2 x (1,10)^${t+1} ; PV = D / (1,14)^${t+1}`,`${fm(d)} / ${fm(1.14**(t+1),4)}`,'$'+fm(pvd[t])]),['Jumlah PV dividen fase 1','jumlah PV D1 sampai D5',pvd.map(x=>fm(x)).join(' + '),'$'+fm(pvd.reduce((a,b)=>a+b,0))],['D6','D6 = D5 x (1 + g2)',`${fm(D[4])} x 1,06`,'$'+fm(D6)],['Harga akhir fase 1 (P5)','P5 = D6 / (ke - g2)',`${fm(D6)} / 0,08`,'$'+fm(P5)],['PV dari P5','P5 / (1,14)^5',`${fm(P5)} / ${fm(1.14**5,4)}`,'$'+fm(pP)],['Nilai saham','V = PV dividen fase 1 + PV P5',`${fm(pvd.reduce((a,b)=>a+b,0))} + ${fm(pP)}`,'$'+fm(V)]],
cara:['Bagi waktu menjadi dua fase: pertumbuhan tinggi (tahun 1 sampai 5) dan pertumbuhan stabil (setelah tahun 5).','Fase 1: hitung dividen tiap tahun D_t = D0 (1+g1)^t lalu diskontokan satu per satu.','Fase 2: pada akhir tahun 5 pakai model pertumbuhan konstan: P5 = D6 / (ke - g2), dengan D6 = D5 (1+g2).','Diskontokan P5 mundur 5 tahun ke hari ini.','Jumlahkan fase 1 dan fase 2.'],
jebak:'Eksponen fase 2 dimulai dari D5, bukan D0. Dan P5 harus didiskonto 5 periode, bukan 6.',s:W2+', no. 37-39'}},

// ================== 2. LAPORAN KEUANGAN DAN RASIO (data PT Maju Bersama, Excel Week 6 Q3)
(()=>{const DT=`<p class="note">Data PT Maju Bersama 2024 (dalam $ ribu): Penjualan 1.900; HPP 1.220; Operating profit (EBIT) 410; Beban bunga 44; Laba bersih 220; Kas 160; Piutang 265; Persediaan 220; Aktiva lancar 715; Total aset 1.675; Utang usaha 170; Utang lancar 370; Utang jangka panjang 430; Total liabilitas 800; Ekuitas 875.</p>`;
return[
()=>{const v=(715-220)/370;return{t:2,h:'Quick ratio',q:'Hitung <b>quick (acid-test) ratio</b> PT Maju Bersama tahun 2024 (dalam kali).'+DT,a:v,u:'x',d:2,
steps:[['Aktiva paling likuid','aktiva lancar - persediaan',`715 - 220`,'495'],['Quick ratio','(Aktiva lancar - persediaan) / utang lancar',`495 / 370`,fm(v)+'x']],
cara:['Ambil aktiva lancar dari neraca.','Kurangi persediaan (dan bila ada, biaya dibayar di muka).','Bagi dengan utang lancar.','Tafsirkan: di atas 1x berarti aset likuid cukup menutup utang jangka pendek tanpa menjual persediaan.'],jebak:'Jangan mengurangi piutang. Hanya persediaan yang dikeluarkan.',s:W3+', no. 22-23; data '+W6}},
()=>{const v=410/44;return{t:2,h:'Interest coverage',q:'Hitung <b>interest coverage ratio</b> PT Maju Bersama tahun 2024 (dalam kali).'+DT,a:v,u:'x',d:2,
steps:[['Interest coverage','EBIT / beban bunga',`410 / 44`,fm(v)+'x']],
cara:['Gunakan EBIT (operating profit), bukan laba bersih.','Bagi dengan beban bunga.','Bandingkan dengan median industri; semakin tinggi semakin aman.'],jebak:'Pembilang adalah laba sebelum bunga dan pajak (410). Memakai laba bersih (220) menghasilkan 5x yang keliru.',s:W3+', no. 31-33'}},
()=>{const d=265/1900*365,i=220/1220*365,p=170/1220*365,v=d+i-p;return{t:2,h:'Cash cycle',q:'Hitung <b>cash cycle (hari)</b> PT Maju Bersama 2024 (365 hari). Piutang dihitung dari penjualan, persediaan dan utang usaha dari HPP.'+DT,a:v,u:' hari',d:1,
steps:[['Hari piutang (DSO)','piutang / penjualan x 365',`265 / 1.900 x 365`,fm(d)+' hari'],['Hari persediaan (DIO)','persediaan / HPP x 365',`220 / 1.220 x 365`,fm(i)+' hari'],['Hari utang usaha (DPO)','utang usaha / HPP x 365',`170 / 1.220 x 365`,fm(p)+' hari'],['Operating cycle','DSO + DIO',`${fm(d)} + ${fm(i)}`,fm(d+i)+' hari'],['Cash cycle','operating cycle - DPO',`${fm(d+i)} - ${fm(p)}`,fm(v)+' hari']],
cara:['Hitung tiga komponen: DSO, DIO, DPO. Ingat dasar masing-masing: penjualan untuk piutang, HPP untuk persediaan dan utang usaha.','Operating cycle = DSO + DIO (dari beli bahan sampai kas diterima).','Cash cycle = operating cycle - DPO (hanya masa dana benar-benar keluar).','Semakin pendek cash cycle, semakin sedikit modal kerja yang tertahan.'],jebak:'Jangan memakai penjualan untuk persediaan atau utang usaha. Hitungan memakai saldo akhir; jika soal memberi rata-rata saldo, ikuti soal.',s:W3+', no. 35-43'}},
()=>{const m=220/1900,t=1900/1675,e=1675/875,v=m*t*e;return{t:2,h:'ROE dengan pendekatan Du Pont',q:'Hitung <b>ROE (%)</b> PT Maju Bersama 2024 memakai Du Pont: net profit margin x total asset turnover x equity multiplier.'+DT,a:v*100,u:'%',d:2,
steps:[['Net profit margin','laba bersih / penjualan',`220 / 1.900`,pf(m)],['Total asset turnover','penjualan / total aset',`1.900 / 1.675`,fm(t,4)+'x'],['Equity multiplier','total aset / ekuitas',`1.675 / 875`,fm(e,4)+'x'],['ROE','margin x TAT x multiplier',`${fm(m,4)} x ${fm(t,4)} x ${fm(e,4)}`,pf(v)],['Cek langsung','laba bersih / ekuitas',`220 / 875`,pf(220/875)]],
cara:['Tuliskan rumus Du Pont: ROE = (NI/Sales) x (Sales/Assets) x (Assets/Equity).','Hitung ketiga komponen secara terpisah (profitabilitas, efisiensi aset, leverage).','Kalikan. Penjualan dan total aset saling meniadakan sehingga hasilnya sama dengan NI/Ekuitas.','Gunakan pecahannya untuk analisis: ROE tinggi karena margin, perputaran, atau leverage?'],jebak:'Jawab dalam persen. Jika hasil Du Pont tidak sama dengan NI / ekuitas, ada komponen yang salah dihitung.',s:W3+', no. 53-57'}},
()=>{const v=220/123*100;return{t:2,h:'Index analysis',q:'Laba bersih PT Maju Bersama: 2020 = <b>$123</b>, 2024 = <b>$220</b> (ribu). Dengan <b>2020 sebagai tahun dasar (=100)</b>, berapa indeks laba bersih 2024?',a:v,d:2,
steps:[['Indeks','indeks = nilai tahun t / nilai tahun dasar x 100',`220 / 123 x 100`,fm(v)],['Tafsir','indeks - 100 = persen perubahan',`${fm(v)} - 100`,'naik '+fm(v-100)+'% dibanding 2020']],
cara:['Tentukan tahun dasar dan beri nilai 100.','Bagi nilai tahun yang dianalisis dengan nilai tahun dasar.','Kalikan 100.','Indeks di atas 100 berarti naik, di bawah 100 berarti turun dari tahun dasar.'],jebak:'Pembagi selalu tahun dasar, bukan tahun sebelumnya. Itu yang membedakan index analysis dari persentase pertumbuhan tahunan.',s:W3+', no. 63-65'}},
()=>{const v=800/1675;return{t:2,h:'Debt to total assets',q:'Hitung <b>debt to total assets ratio (%)</b> PT Maju Bersama 2024 dan tafsirkan komposisi pembiayaannya.'+DT,a:v*100,u:'%',d:2,
steps:[['Debt to total assets','total utang / total aset',`800 / 1.675`,pf(v)],['Sisa dari ekuitas','1 - rasio',`1 - ${fm(v,4)}`,pf(1-v)]],
cara:['Ambil total utang (lancar + jangka panjang) dan total aset.','Bagi, lalu ubah ke persen.','Tafsirkan: bagian aset yang dibiayai kreditor; sisanya dibiayai pemegang saham.','Semakin tinggi, semakin besar risiko keuangan.'],jebak:'Gunakan total utang (800), bukan hanya utang jangka panjang (430).',s:W3+', no. 27-28'}}
]})().map(f=>f).reduce((a,f)=>a.concat(f),[]) ,

// ================== 3. CASH FLOW DAN PROYEKSI
(()=>{
const BS=[['Cash',210,200,'A'],['Accounts receivable',590,620,'A'],['Inventories',1420,1350,'A'],['Prepaid expenses',30,22,'A'],['Accumulated tax prepayments',32,35,'A'],['Net fixed assets',960,900,'A'],['Investment, long term',115,130,'A'],['Other assets, long term',200,200,'A'],['Bank loans & notes payable',490,450,'L'],['Accounts payable',150,160,'L'],['Accrued taxes',42,50,'L'],['Other accrued liabilities',130,110,'L'],['Long-term debt',660,700,'L'],['Common stock',430,430,'L'],['Additional paid-in capital',380,360,'L'],['Retained earnings',1275,1197,'L']];
const SJ=[[2020,2000,1500,320],[2021,2200,1620,340],[2022,2400,1740,360]];
const sg=SJ.map((r,i)=>i?r[1]/SJ[i-1][1]-1:null).filter(x=>x!==null),gs=avg(sg),S23=2400*(1+gs),cr=SJ.map(r=>r[2]/r[1]),cra=avg(cr),C23=S23*cra,G23=S23-C23,SGA=22*12*1.06+6*12*1.08+9*12+3*12*1.05,OI=G23-SGA;
const SJT=tbl(['Pos ($ ribu)','2020','2021','2022'],[['Net sales',...SJ.map(r=>fm(r[1],0))],['COGS',...SJ.map(r=>fm(r[2],0))],['SG&A',...SJ.map(r=>fm(r[3],0))]])+`<p class="note">Info SG&A 2023: gaji $22/bulan (2022) naik 6%; utilitas $6/bulan naik 8%; sewa tetap $9/bulan; lain-lain $3/bulan naik 5%.</p>`;
const MB=[[2020,1200,780,180,150,120],[2021,1350,880,195,165,130],[2022,1500,970,215,180,140],[2023,1700,1100,240,200,155],[2024,1900,1220,265,220,170]];
const sgm=MB.map((r,i)=>i?r[1]/MB[i-1][1]-1:null).filter(x=>x!==null),gm=avg(sgm),S25=1900*(1+gm),crm=avg(MB.map(r=>r[2]/r[1])),C25=S25*crm,dso=avg(MB.map(r=>r[3]/r[1]*365)),dio=avg(MB.map(r=>r[4]/r[2]*365)),dpo=avg(MB.map(r=>r[5]/r[2]*365));
const MBT=tbl(['Pos ($ ribu)','2020','2021','2022','2023','2024'],[['Net sales',...MB.map(r=>fm(r[1],0))],['COGS',...MB.map(r=>fm(r[2],0))],['Piutang',...MB.map(r=>fm(r[3],0))],['Persediaan',...MB.map(r=>fm(r[4],0))],['Utang usaha',...MB.map(r=>fm(r[5],0))]]);
const mbSteps=[['Pertumbuhan penjualan tiap tahun','g = penjualan t / penjualan t-1 - 1',sgm.map(x=>pf(x)).join(' ; '),'rata-rata '+pf(gm)],['Penjualan 2025','1.900 x (1 + rata-rata g)',`1.900 x ${fm(1+gm,4)}`,fm(S25)]];
const fc=(kind)=>{const lab=kind=='ar'?'Piutang':kind=='inv'?'Persediaan':'Utang usaha',idx=kind=='ar'?3:kind=='inv'?4:5,d=kind=='ar'?dso:kind=='inv'?dio:dpo,base=kind=='ar'?S25:C25,res=base*d/365,nm=kind=='ar'?'DSO':kind=='inv'?'DIO':'DPO',bn=kind=='ar'?'penjualan':'HPP',baseH=kind=='ar'?'penjualan':'HPP';
const steps=[...mbSteps];if(kind!='ar')steps.push(['Rasio HPP terhadap penjualan','HPP / penjualan, lalu dirata-ratakan',MB.map(r=>fm(r[2]/r[1],3)).join(' ; '),'rata-rata '+fm(crm,4)],['HPP 2025','penjualan 2025 x rata-rata rasio',`${fm(S25)} x ${fm(crm,4)}`,fm(C25)]);
steps.push([nm+' tiap tahun',`${lab} / ${bn} x 365`,MB.map(r=>fm(r[idx]/(kind=='ar'?r[1]:r[2])*365,1)).join(' ; '),'rata-rata '+fm(d,2)+' hari'],[lab+' 2025',`${bn} 2025 x ${nm} / 365`,`${fm(base)} x ${fm(d,2)} / 365`,'$'+fm(res)]);
return{t:3,h:'Proyeksi '+lab.toLowerCase()+' 2025',q:`Proyeksikan <b>${lab.toLowerCase()} PT Maju Bersama tahun 2025</b>. Gunakan rata-rata pertumbuhan penjualan historis${kind=='ar'?'':', rata-rata rasio HPP/penjualan'} dan rata-rata ${nm} 5 tahun (365 hari).${MBT}`,a:res,pre:'$',d:2,steps,
cara:kind=='ar'?['Proyeksikan penjualan 2025 dengan rata-rata pertumbuhan tahunan 2021-2024.','Hitung DSO tiap tahun = piutang / penjualan x 365, lalu rata-ratakan.','Piutang 2025 = penjualan 2025 x DSO rata-rata / 365.','Cek kewajaran: pertumbuhan piutang seharusnya sejalan dengan pertumbuhan penjualan.']:['Proyeksikan penjualan 2025 dengan rata-rata pertumbuhan.','Proyeksikan HPP 2025 = penjualan 2025 x rata-rata rasio HPP/penjualan.',`Hitung ${nm} tiap tahun = ${lab.toLowerCase()} / HPP x 365 dan rata-ratakan.`,`${lab} 2025 = HPP 2025 x ${nm} / 365.`],
jebak:kind=='ar'?'Rata-rata pertumbuhan dihitung dari 4 angka pertumbuhan (2021-2024), bukan 5. DSO dasarnya penjualan.':`${lab} bergantung pada HPP, bukan penjualan. Rata-rata pertumbuhan dihitung dari 4 angka (2021-2024).`,s:W6+', sheet Answer of Q3'}};
return[
()=>{const rows=BS.map(r=>{const dl=r[1]-r[2],src=(r[3]=='A'&&dl<0)||(r[3]=='L'&&dl>0),use=dl!=0&&!src;return[r[0],fm(r[1],0),fm(r[2],0),dl==0?'-':(dl>0?'+':'')+fm(dl,0),src?fm(Math.abs(dl),0):'',use?fm(Math.abs(dl),0):'']}),S=BS.reduce((s,r)=>{const dl=r[1]-r[2];return s+(((r[3]=='A'&&dl<0)||(r[3]=='L'&&dl>0))?Math.abs(dl):0)},0),U=BS.reduce((s,r)=>{const dl=r[1]-r[2];return s+((dl!=0&&!((r[3]=='A'&&dl<0)||(r[3]=='L'&&dl>0)))?Math.abs(dl):0)},0);
return{t:3,h:'Total sumber dan penggunaan dana',q:'Neraca PT Andika Prima (ribu rupiah). Tentukan <b>total sumber dana</b> (sources of funds) periode 31 Maret 2022 ke 31 Maret 2023.'+tbl(['Pos','31 Mar 2023','31 Mar 2022'],BS.map(r=>[r[0],fm(r[1],0),fm(r[2],0)])),a:S,pre:'Rp',u:' ribu',d:0,
steps:[{h:'<p class="note">Selisih tiap pos dan klasifikasinya (aset turun atau kewajiban/ekuitas naik = sumber):</p>'+tbl(['Pos','2023','2022','Selisih','Sumber','Penggunaan'],rows)},['Total sumber','jumlah kolom Sumber','30 + 3 + 15 + 40 + 20 + 20 + 78',fm(S,0)],['Total penggunaan','jumlah kolom Penggunaan','10 + 70 + 8 + 60 + 10 + 8 + 40',fm(U,0)+' (sama dengan sumber, neraca seimbang)']],
cara:['Hitung selisih setiap pos: 2023 dikurangi 2022.','Aset naik = penggunaan; aset turun = sumber.','Kewajiban atau ekuitas naik = sumber; turun = penggunaan.','Pos yang tidak berubah (other assets, common stock) diabaikan.','Jumlahkan kolom sumber dan kolom penggunaan. Keduanya harus sama; jika tidak, ada kesalahan klasifikasi.'],
jebak:'Jangan menjumlah subtotal seperti "current assets". Pada tabel jawaban Excel, kolom penggunaan tertulis 261 karena subtotal aktiva lancar (55) ikut terjumlah; angka yang benar 206.',s:W6+', sheet Q1 dan Answer of Q1'}},
()=>{return{t:3,h:'Proyeksi penjualan dengan rata-rata pertumbuhan',q:'Proyeksikan <b>net sales 2023</b> PT Sejahtera Abadi dengan <b>rata-rata pertumbuhan penjualan historis</b>.'+SJT,a:S23,pre:'$',d:2,
steps:[['Pertumbuhan 2021','2.200 / 2.000 - 1','',pf(sg[0])],['Pertumbuhan 2022','2.400 / 2.200 - 1','',pf(sg[1])],['Rata-rata pertumbuhan','(g2021 + g2022) / 2',`(${fm(sg[0]*100,3)}% + ${fm(sg[1]*100,3)}%) / 2`,pf(gs,3)],['Net sales 2023','penjualan 2022 x (1 + g rata-rata)',`2.400 x ${fm(1+gs,5)}`,'$'+fm(S23)]],
cara:['Hitung pertumbuhan tiap tahun: penjualan tahun ini / tahun lalu - 1.','Rata-ratakan angka pertumbuhan (3 data penjualan menghasilkan 2 angka pertumbuhan).','Kalikan penjualan tahun terakhir dengan (1 + rata-rata g).'],jebak:'Jumlah angka pertumbuhan selalu satu lebih sedikit dari jumlah tahun data.',s:W6+', sheet Answer of Q2'}},
()=>{return{t:3,h:'Proyeksi COGS dengan rasio rata-rata',q:'Dengan penjualan 2023 hasil proyeksi (rata-rata pertumbuhan) dan <b>rata-rata rasio COGS/penjualan 3 tahun</b>, berapa <b>COGS 2023</b> PT Sejahtera Abadi?'+SJT,a:C23,pre:'$',d:2,
steps:[['Penjualan 2023','2.400 x (1 + rata-rata g)','',fm(S23)],['Rasio COGS/penjualan','1.500/2.000 ; 1.620/2.200 ; 1.740/2.400',cr.map(x=>fm(x,4)).join(' ; '),'rata-rata '+fm(cra,5)],['COGS 2023','penjualan 2023 x rasio rata-rata',`${fm(S23)} x ${fm(cra,5)}`,'$'+fm(C23)]],
cara:['Proyeksikan penjualan 2023 lebih dulu.','Hitung rasio COGS/penjualan tiap tahun lalu rata-ratakan.','Kalikan rasio rata-rata dengan penjualan proyeksi.'],jebak:'Rasio COGS dikali penjualan proyeksi 2023, bukan penjualan 2022.',s:W6+', sheet Answer of Q2'}},
()=>{return{t:3,h:'Forecast operating income 2023',q:'Susun proyeksi laba usaha dan hitung <b>operating income 2023</b> PT Sejahtera Abadi: penjualan dengan rata-rata pertumbuhan, COGS dengan rasio rata-rata, SG&A dari rincian biaya.'+SJT,a:OI,pre:'$',d:2,
steps:[['Net sales 2023','2.400 x (1 + g rata-rata)','',fm(S23)],['COGS 2023','penjualan x rasio rata-rata',`${fm(S23)} x ${fm(cra,5)}`,fm(C23)],['Gross profit','penjualan - COGS',`${fm(S23)} - ${fm(C23)}`,fm(G23)],['Gaji','22 x 12 x 1,06','',fm(22*12*1.06)],['Utilitas','6 x 12 x 1,08','',fm(6*12*1.08)],['Sewa','9 x 12','',fm(108)],['Lain-lain','3 x 12 x 1,05','',fm(3*12*1.05)],['Total SG&A','jumlah komponen','',fm(SGA)],['Operating income','gross profit - SG&A',`${fm(G23)} - ${fm(SGA)}`,'$'+fm(OI)]],
cara:['Kerjakan berurutan: penjualan, COGS, gross profit, SG&A, operating income.','Untuk SG&A, ubah biaya bulanan menjadi tahunan (x 12) lalu terapkan kenaikan masing-masing.','Biaya tetap seperti sewa tidak dinaikkan.','Operating income = gross profit - SG&A.'],jebak:'Perhatikan: rincian SG&A bulanan x 12 totalnya $480 (2022), padahal SG&A historis di tabel $360. Soal ini mengikuti rincian di keterangan soal (hasil Excel: $503,4), jadi ikuti data yang diberikan.',s:W6+', sheet Answer of Q2'}},
()=>fc('ar'),()=>fc('inv'),()=>fc('ap')
]})(),

// ================== 4. RISIKO DAN RETURN
(()=>{const ST=(n,p,r)=>tbl(['Kondisi','Peluang','Return '+n],[['Resesi',p[0]+'%',r[0]+'%'],['Normal',p[1]+'%',r[1]+'%'],['Boom',p[2]+'%',r[2]+'%']]);
const stat=(p,r)=>{const E=p.reduce((s,x,j)=>s+x*r[j],0),V=p.reduce((s,x,j)=>s+x*(r[j]-E)**2,0);return{E,V,sd:Math.sqrt(V)}};
const pA=[.25,.5,.25],rA=[-5,10,25],pB=[.25,.5,.25],rB=[4,8,12],sA=stat(pA,rA),sB=stat(pB,rB);
const stepsStat=(n,p,r,s)=>[['Expected return','E(R) = jumlah p x R',p.map((x,j)=>`${fm(x,2)} x ${r[j]}`).join(' + '),fm(s.E)+'%'],['Varians','Var = jumlah p x (R - E)^2',p.map((x,j)=>`${fm(x,2)} x (${r[j]} - ${fm(s.E)})^2`).join(' + '),fm(s.V)],['Standar deviasi','sigma = akar(Var)',`akar(${fm(s.V)})`,fm(s.sd)+'%'],['Coefficient of variation','CV = sigma / E(R)',`${fm(s.sd)} / ${fm(s.E)}`,fm(s.sd/s.E,3)]];
const caraStat=['Hitung expected return: jumlahkan peluang x return tiap kondisi.','Hitung selisih tiap return dari expected return, kuadratkan, kalikan peluang, jumlahkan: itu varians.','Standar deviasi = akar varians.','CV = standar deviasi / expected return. Pakai CV untuk membandingkan investasi yang expected return-nya berbeda.'];
const NPV=[-200,150,400],pN=[.2,.5,.3],sN=stat(pN,NPV);
const s1=10,s2=8,rho=.3,sp=Math.sqrt(s1*s1+s2*s2+2*rho*s1*s2);
return[
()=>({t:4,h:'Standar deviasi return saham',q:'Hitung <b>standar deviasi (%)</b> return Saham Teknologi A.'+ST('A',[25,50,25],rA),a:sA.sd,u:'%',d:2,steps:stepsStat('A',pA,rA,sA),cara:caraStat,jebak:'Kuadratkan selisih sebelum dikali peluang. Standar deviasi adalah akar dari varians, bukan varians itu sendiri.',s:W7+', no. 5-7; Lab Risiko'}),
()=>({t:4,h:'Coefficient of variation',q:'Hitung <b>coefficient of variation (CV)</b> Saham Konsumsi B, lalu bandingkan dengan Saham A (E = 10%, sigma = 10,61%).'+ST('B',[25,50,25],rB),a:sB.sd/sB.E,d:3,steps:[...stepsStat('B',pB,rB,sB),['Perbandingan','CV A = 10,61 / 10 = 1,061 ; CV B = '+fm(sB.sd/sB.E,3),'','B memiliki risiko per unit return jauh lebih kecil']],cara:caraStat,jebak:'A punya return harapan lebih tinggi, tetapi CV menunjukkan risikonya per unit return juga jauh lebih besar. Pilihan bergantung pada toleransi risiko.',s:W7+', no. 8'}),
()=>{const v=5+1.3*(11-5);return{t:4,h:'Required return menurut CAPM',q:'Risk-free rate <b>5%</b>, return pasar <b>11%</b>, beta saham <b>1,3</b>. Berapa required return (%) menurut CAPM?',a:v,u:'%',d:2,steps:[['Premi risiko pasar','Rm - Rf',`11 - 5`,'6%'],['Required return','k = Rf + beta x (Rm - Rf)',`5 + 1,3 x 6`,fm(v)+'%'],['Sifat saham','beta > 1','1,3 > 1','agresif']],cara:['Hitung premi risiko pasar: Rm - Rf.','Kalikan dengan beta saham.','Tambahkan risk-free rate.','Tafsirkan: beta di atas 1 berarti required return lebih tinggi dari return pasar.'],jebak:'Yang dikali beta adalah premi pasar (Rm - Rf), bukan Rm.',s:B5}},
()=>{const w=[.4,.35,.25],r=[12,9,15],v=w.reduce((s,x,j)=>s+x*r[j],0);return{t:4,h:'Return portofolio',q:'Portofolio: <b>40% saham A (12%), 35% saham B (9%), 25% saham C (15%)</b>. Berapa expected return portofolio (%)?',a:v,u:'%',d:2,steps:[['Bobot total','harus 100%','40 + 35 + 25','100%'],['Return portofolio','Rp = jumlah W x R',w.map((x,j)=>`${fm(x,2)} x ${r[j]}`).join(' + '),fm(v)+'%']],cara:['Pastikan jumlah bobot 100%.','Kalikan bobot tiap sekuritas dengan return-nya.','Jumlahkan hasilnya.'],jebak:'Return portofolio adalah rata-rata tertimbang, bukan rata-rata biasa (12%).',s:B5}},
()=>{const v=(54000-50000+2500)/50000;return{t:4,h:'Holding period return',q:'Saham dibeli <b>Rp50.000</b>, setahun kemudian harganya <b>Rp54.000</b> dan selama itu menerima dividen <b>Rp2.500</b>. Berapa return periode kepemilikan (%)?',a:v*100,u:'%',d:2,steps:[['Capital gain','P1 - P0',`54.000 - 50.000`,'4.000'],['Return periode kepemilikan','(P1 - P0 + kas diterima) / P0',`(4.000 + 2.500) / 50.000`,pf(v)],['Pemecahan','dividend yield + capital gains yield',`${pf(2500/50000)} + ${pf(4000/50000)}`,pf(v)]],cara:['Hitung selisih harga: harga akhir - harga awal.','Tambahkan kas yang diterima (dividen).','Bagi dengan harga awal.'],jebak:'Penyebutnya harga awal (P0), bukan harga akhir.',s:B5}},
()=>({t:4,h:'Risiko proyek: standar deviasi NPV',q:'Proyek memiliki tiga kemungkinan NPV (dalam juta rupiah): <b>-200 (peluang 20%), 150 (50%), 400 (30%)</b>. Hitung <b>standar deviasi NPV</b>.',a:sN.sd,u:' juta',d:2,steps:[['Expected NPV','E(NPV) = jumlah p x NPV',pN.map((x,j)=>`${fm(x,2)} x ${NPV[j]}`).join(' + '),fm(sN.E)],['Varians','jumlah p x (NPV - E)^2',pN.map((x,j)=>`${fm(x,2)} x (${NPV[j]} - ${fm(sN.E)})^2`).join(' + '),fm(sN.V)],['Standar deviasi','akar(Var)',`akar(${fm(sN.V)})`,fm(sN.sd)],['CV','sigma / E(NPV)',`${fm(sN.sd)} / ${fm(sN.E)}`,fm(sN.sd/sN.E,3)],['Peluang rugi','peluang NPV < 0','hanya skenario -200','20%']],cara:['Daftar semua skenario NPV beserta peluangnya (jumlah peluang harus 100%).','Hitung E(NPV).','Hitung varians dan standar deviasi.','Interpretasi: expected NPV positif belum cukup; lihat sebaran. Hitung CV dan peluang NPV negatif.'],jebak:'Expected NPV positif bukan sinyal terima yang pasti; risiko harus dipertimbangkan (slide Week 7, no. 14).',s:W7+', no. 12-15'}),
()=>({t:4,h:'Risiko portofolio dua proyek',q:'Dua proyek independen punya standar deviasi NPV <b>$10</b> dan <b>$8</b> (juta), dengan <b>koefisien korelasi 0,3</b>. Berapa standar deviasi NPV gabungan keduanya?',a:sp,pre:'$',u:' juta',d:2,steps:[['Kovarians','cov = rho x sigma1 x sigma2',`0,3 x 10 x 8`,'24'],['Standar deviasi gabungan','sigma = akar(s1^2 + s2^2 + 2 x cov)',`akar(100 + 64 + 2 x 24) = akar(212)`,fm(sp)],['Bandingkan','jumlah sigma tanpa diversifikasi','10 + 8','18 (lebih besar dari '+fm(sp)+')']],cara:['Hitung kovarians = korelasi x sigma1 x sigma2.','Masukkan ke rumus sigma portofolio: akar(s1^2 + s2^2 + 2 x cov).','Bandingkan dengan s1 + s2. Selisihnya adalah manfaat diversifikasi.','Semakin rendah korelasi (bahkan negatif), semakin kecil risiko gabungan.'],jebak:'Standar deviasi tidak bisa dijumlahkan langsung. Hanya jika korelasi = 1 hasilnya sama dengan s1 + s2.',s:W7+', no. 18-21'})
]})()
];
const PRs=[].concat(...PB.map(x=>Array.isArray(x)?x:[x]));
let PRC=null;
const PRL=()=>PRC||(PRC=PRs.map(f=>f()).map((x,i)=>(x.id=i,x)));

/* ================= STATE ================= */
const S={topic:0,qz:{key:'',i:0,ans:[]},pr:{key:'',i:0,st:{}}};
const nav=(mode)=>{S.mode=mode};
function list(mode){const all=mode=='quiz'?QZ.map((x,i)=>({id:i,t:x[0]})):PRL();return S.topic?all.filter(x=>x.t==S.topic):all}
function key(mode){return mode+S.topic}

/* ================= TAMPILAN ================= */
const cnt=(arr,t)=>arr.filter(x=>x[0]==t||x.t==t).length;
function hub(){const pc=PRL();return `<section class="page"><h2>Latihan UTS</h2><p class="lead">Pilih bentuk latihan. Semua soal mengikuti kisi-kisi UTS dan dikerjakan dari materi slide dan Excel yang kamu punya.</p>
<h3>Kisi-kisi UTS</h3><ol>${[1,2,3,4].map(t=>`<li>${TN[t]}${t==1?' (nilai waktu uang, obligasi, saham)':t==2?' (liquidity, leverage, activity, profitability, Du Pont, common-size, index)':t==3?' (sources and uses, proyeksi laporan keuangan)':' (expected return, sigma, CV, CAPM, portofolio, risiko proyek)'}</li>`).join('')}</ol>
<div class="cards"><a href="#/latihan/quiz"><b>Quiz (Teoritis)</b><br><small>${QZ.length} soal pilihan ganda. Setiap soal ada pembahasan: kenapa benar dan kenapa pilihan lain keliru.</small></a><a href="#/latihan/praktik"><b>Praktik (Hitung-hitungan)</b><br><small>${pc.length} soal hitungan. Ada kolom jawaban, langkah hitung lengkap, dan panduan cara mengerjakan di akhir tiap soal.</small></a></div>
<p class="note">Rincian soal: ${[1,2,3,4].map(t=>`${TN[t]} (${cnt(QZ,t)} quiz, ${cnt(pc,t)} praktik)`).join('; ')}.</p></section>`}
const chips=(mode)=>`<div class="chipbar" role="group" aria-label="Pilih topik">${[0,1,2,3,4].map(t=>`<button class="btn ${S.topic==t?'on':''}" onclick="LT.topic(${t})">${TN[t]}</button>`).join('')}</div>`;
const head=(mode)=>`<p><a href="#/latihan">Semua latihan</a> &nbsp; <a href="#/latihan/${mode=='quiz'?'praktik':'quiz'}">Pindah ke ${mode=='quiz'?'Praktik':'Quiz'}</a></p><h2>${mode=='quiz'?'Quiz (Teoritis)':'Praktik (Hitung-hitungan)'}</h2>${chips(mode)}`;

function quizView(){const ls=list('quiz'),k=key('quiz');if(S.qz.key!=k)S.qz={key:k,i:0,ans:[]};const z=S.qz;let h=`<section class="page">${head('quiz')}`;
if(z.i>=ls.length){const sc=ls.filter((x,j)=>z.ans[j]==QZ[x.id][3]).length;const by=[1,2,3,4].map(t=>{const idx=ls.map((x,j)=>[x,j]).filter(([x])=>x.t==t);return idx.length?`<div class="res"><span>${TN[t]}</span><strong>${idx.filter(([x,j])=>z.ans[j]==QZ[x.id][3]).length} dari ${idx.length}</strong></div>`:''}).join('');
const wr=ls.map((x,j)=>[x,j]).filter(([x,j])=>z.ans[j]!=QZ[x.id][3]);
h+=`<h3>Hasil</h3><p class="lead">Skormu ${sc} dari ${ls.length} (${fm(sc/ls.length*100,0)}%).</p>${by}<p>${sc/ls.length>=.8?'Kuat. Lanjut ke Praktik untuk mengasah hitungan.':'Pelajari pembahasan soal yang salah di bawah, lalu ulangi quiz.'}</p>${wr.length?`<h3>Soal yang perlu diulang</h3>${wr.map(([x,j])=>{const q=QZ[x.id];return `<details class="fc"><summary><b>${TL[q[0]].slice(3)}</b>: ${q[1]}</summary><p>Jawabanmu: ${z.ans[j]==null?'(kosong)':q[2][z.ans[j]]}</p><p class="rs">Jawaban benar: ${q[2][q[3]]}</p><p class="ex">${q[4]}</p><p class="use">Sumber: ${q[5]}</p></details>`}).join('')}`:''}<button class="btn" onclick="LT.resetQ()">Ulangi quiz</button><a class="btn" href="#/latihan/praktik">Lanjut ke Praktik</a>`;return h+'</section>'}
const x=QZ[ls[z.i].id],a=z.ans[z.i],ans=a!=null;
h+=`<h3>Soal ${z.i+1} dari ${ls.length} <span class="chip l3">${TN[x[0]]}</span></h3><p class="lead">${x[1]}</p>${x[2].map((o,j)=>`<button class="opt ${!ans?'':j==x[3]?'ok':j==a?'no':''}" ${ans?'disabled':''} onclick="LT.pick(${j})">${String.fromCharCode(65+j)}. ${o}</button>`).join('')}`;
if(ans)h+=`<p class="rs">${a==x[3]?'Benar.':'Belum tepat. Jawaban yang benar: '+String.fromCharCode(65+x[3])+'.'}</p><div class="ex"><b>Pembahasan</b><p>${x[4]}</p><p class="use">Sumber: ${x[5]}</p></div><button class="btn" onclick="LT.next()">${z.i+1<ls.length?'Soal berikutnya':'Lihat hasil'}</button>`;
return h+'</section>'}

const parse=s=>{s=String(s).replace(/[%\s$]|Rp|rb|ribu|juta|hari|x$/gi,'');if(!s)return NaN;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');else if(/^-?\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,'');return parseFloat(s)};
const okAns=(u,it)=>isFinite(u)&&Math.abs(u-it.a)<=Math.max(Math.abs(it.a)*(it.tol||.006),it.d===0?.5:.006);
const shown=it=>(it.pre||'')+fm(it.a,it.d==null?2:it.d)+(it.u||'');
function praktikView(){const ls=list('praktik'),k=key('praktik');if(S.pr.key!=k)S.pr={key:k,i:0,st:{}};const p=S.pr,it=ls[p.i],st=p.st[it.id]||{v:'',chk:false,rev:false,ok:null};
let h=`<section class="page">${head('praktik')}<div class="qnav">${ls.map((x,j)=>{const s=p.st[x.id];return `<button class="qn ${j==p.i?'cur':''} ${s&&s.chk?(s.ok?'ok':'no'):s&&s.rev?'rv':''}" onclick="LT.go(${j})" aria-label="Soal ${j+1}">${j+1}</button>`}).join('')}</div>
<h3>Soal ${p.i+1} dari ${ls.length}: ${it.h} <span class="chip l3">${TN[it.t]}</span></h3><div class="lead" style="font-style:normal;max-width:none">${it.q}</div>
<label for="ans">Jawabanmu${it.u&&it.u.trim()=='%'?' (dalam %)':it.pre=='$'?' (dalam $)':''}</label><input id="ans" type="text" inputmode="decimal" autocomplete="off" value="${st.v.replace(/"/g,'&quot;')}" placeholder="contoh: 1234,56" ${st.chk?'disabled':''} onkeydown="if(event.key=='Enter')LT.check()">
<p>${st.chk?'':`<button class="btn" onclick="LT.check()">Periksa jawaban</button>`}${st.chk||st.rev?'':`<button class="btn" style="background:var(--wood2)" onclick="LT.reveal()">Lihat pembahasan</button>`}</p>`;
if(st.chk)h+=`<p class="rs ${st.ok?'up':'dn'}">${st.ok?'Benar! ':'Belum tepat. '}Jawaban yang benar: ${shown(it)}${st.ok?'':'. Cek langkah di bawah untuk melihat di mana selisihnya.'}</p>`;
if(st.chk||st.rev){h+=`<h3>Pembahasan langkah demi langkah</h3>${it.steps.map(x=>x.h?`<div class="tw">${x.h}</div>`:`<div class="stp"><b>${x[0]}</b>${x[1]?`<code>${x[1]}</code>`:''}${x[2]?`<div class="sub">${x[2]}</div>`:''}${x[3]?`<div class="rs">= ${x[3]}</div>`:''}</div>`).join('')}<p class="rs">Jawaban akhir: ${shown(it)}</p>
<div class="cara"><h3>Cara mengerjakan soal seperti ini</h3><ol>${it.cara.map(c=>`<li>${c}</li>`).join('')}</ol><p class="trap"><b>Jebakan yang sering muncul:</b> ${it.jebak}</p><p class="use">Sumber soal: ${it.s}</p></div>`}
h+=`<p>${p.i>0?`<button class="btn" onclick="LT.go(${p.i-1})">Sebelumnya</button>`:''}${p.i+1<ls.length?`<button class="btn" onclick="LT.go(${p.i+1})">Berikutnya</button>`:''}</p></section>`;
setTimeout(()=>{const e=document.getElementById('ans');if(e&&!e.disabled)e.focus()},0);return h}

window.latihan=function(a){if(a=='quiz')return quizView();if(a=='praktik')return praktikView();return hub()};
const re=()=>{render()};
window.LT={
topic(t){S.topic=t;re()},
pick(j){const z=S.qz;if(z.ans[z.i]==null){z.ans[z.i]=j;re()}},
next(){S.qz.i++;re()},
resetQ(){S.qz={key:'',i:0,ans:[]};re()},
go(j){const p=S.pr,e=document.getElementById('ans'),it=list('praktik')[p.i];if(e&&it&&!(p.st[it.id]&&p.st[it.id].chk)){const s=p.st[it.id]||(p.st[it.id]={v:'',chk:false,rev:false,ok:null});s.v=e.value}p.i=j;re();scrollTo(0,0)},
check(){const p=S.pr,it=list('praktik')[p.i],e=document.getElementById('ans'),s=p.st[it.id]||(p.st[it.id]={v:'',chk:false,rev:false,ok:null});if(s.chk)return;s.v=e.value;if(!s.v.trim()){e.focus();return}s.chk=true;s.ok=okAns(parse(s.v),it);re()},
reveal(){const p=S.pr,it=list('praktik')[p.i],e=document.getElementById('ans'),s=p.st[it.id]||(p.st[it.id]={v:'',chk:false,rev:false,ok:null});s.v=e?e.value:'';s.rev=true;re()}
};
window.LT_DATA={QZ,PRL};
})();
