// Buku Rasio. Definisi rumus mengacu pada Bab 6 buku. Parameter (cut) adalah PEDOMAN UMUM, bukan standar baku dan bukan dari buku.
const LV=["Sangat Buruk","Buruk","Cukup","Baik","Sangat Baik"];
const fv=(v,f)=>!isFinite(v)?'tak terdefinisi':f=='%'?pc(v):f=='h'?$(v)+' hari':f=='rp'?'Rp '+$(v):$(v)+'x';
const rate=(v,r)=>{if(!isFinite(v)||r.nr)return -1;const c=r.cut;return r.dir=='hi'?(v<c[0]?0:v<c[1]?1:v<c[2]?2:v<c[3]?3:4):(v>c[0]?0:v>c[1]?1:v>c[2]?2:v>c[3]?3:4)};
const rng=r=>{const c=r.cut,f=v=>fv(v,r.fm);return r.dir=='hi'?[`di bawah ${f(c[0])}`,`${f(c[0])} sampai di bawah ${f(c[1])}`,`${f(c[1])} sampai di bawah ${f(c[2])}`,`${f(c[2])} sampai di bawah ${f(c[3])}`,`${f(c[3])} atau lebih`]:[`di atas ${f(c[0])}`,`di atas ${f(c[1])} sampai ${f(c[0])}`,`di atas ${f(c[2])} sampai ${f(c[1])}`,`di atas ${f(c[3])} sampai ${f(c[2])}`,`${f(c[3])} atau kurang`]};
const RK=[
{id:"likuiditas",n:"Likuiditas",q:"Mampukah perusahaan membayar utang jangka pendeknya?",d:"Rasio likuiditas membandingkan aset yang cepat menjadi kas dengan kewajiban yang segera jatuh tempo. Paling diperhatikan oleh kreditor jangka pendek dan pemasok."},
{id:"leverage",n:"Leverage (utang)",q:"Seberapa besar perusahaan dibiayai utang, dan seberapa tebal bantalan bagi kreditor?",d:"Rasio leverage menunjukkan proporsi pendanaan dari kreditor dibanding pemilik. Makin besar utang, makin besar risiko keuangan, tetapi bunga utang mengurangi pajak."},
{id:"coverage",n:"Coverage",q:"Cukupkah laba untuk menutup beban keuangan?",d:"Rasio coverage menghubungkan beban keuangan tetap dengan kemampuan perusahaan melayaninya. Lembaga pemeringkat obligasi memakainya secara luas."},
{id:"aktivitas",n:"Aktivitas (efisiensi)",q:"Seberapa cepat aset berputar menjadi penjualan dan kas?",d:"Disebut juga rasio efisiensi atau perputaran. Mengukur seberapa efektif perusahaan memakai aset, terutama piutang dan persediaan."},
{id:"profitabilitas",n:"Profitabilitas",q:"Seberapa besar laba dari penjualan dan dari investasi?",d:"Dua jenis: profitabilitas terhadap penjualan (margin) dan terhadap investasi (ROA dan ROE). Bersama-sama menunjukkan efektivitas operasi secara keseluruhan."},
{id:"pasar",n:"Pasar saham (valuasi)",q:"Berapa laba, nilai buku, dan dividen per lembar saham, dan bagaimana pasar menghargainya?",d:"Rasio nilai pasar menghubungkan angka laporan keuangan dengan harga saham. Berbeda dari lima kelompok lain, rasio ini menilai harga, bukan kinerja, sehingga dibaca sebagai perbandingan (dengan industri dan sejarah sendiri), bukan sebagai Baik atau Buruk. Kelompok ini tambahan di luar Bab 6; kaitannya dengan buku ada di Bab 4 (return saham = dividend yield + capital gains yield) dan Bab 5 (efisiensi pasar)."}];
const D=y=>{const rt=y.sales/y.ar,it=y.cogs/y.inv,rtd=365/rt,itd=365/it;return{rt,it,rtd,itd,ptd:y.ap*365/y.cogs,oc:rtd+itd}};
const RS=[
{id:"cr",k:"likuiditas",n:"Current ratio",f:"Aktiva lancar / Utang lancar",v:[["Aktiva lancar","Kas, surat berharga, piutang, persediaan"],["Utang lancar","Kewajiban yang jatuh tempo dalam satu tahun"]],r:"Berapa rupiah aktiva lancar untuk tiap rupiah utang lancar. Makin tinggi, makin besar kemampuan membayar tagihan.",w:"Ukuran kasar karena tidak membedakan kualitas aktiva lancar: perusahaan yang aktiva lancarnya kebanyakan persediaan kurang likuid daripada yang banyak kas dan piutang. Terlalu tinggi (misalnya di atas 3) juga perlu dicurigai sebagai dana menganggur yang mengorbankan profitabilitas.",dir:"hi",cut:[1,1.2,1.5,2],fm:"x",fn:y=>y.ca/y.cl,sub:y=>`${$(y.ca)} / ${$(y.cl)}`},
{id:"qr",k:"likuiditas",n:"Quick (acid-test) ratio",f:"(Aktiva lancar - Persediaan) / Utang lancar",v:[["Persediaan","Dikeluarkan karena paling lambat dicairkan menjadi kas"]],r:"Uji likuiditas yang lebih keras: mampukah membayar utang lancar tanpa menjual persediaan?",w:"Bandingkan dengan current ratio. Selisih yang besar berarti likuiditas bergantung pada persediaan, yang kualitasnya perlu dicek.",dir:"hi",cut:[.5,.8,1,1.5],fm:"x",fn:y=>(y.ca-y.inv)/y.cl,sub:y=>`(${$(y.ca)} - ${$(y.inv)}) / ${$(y.cl)}`},
{id:"cash",k:"likuiditas",n:"Cash ratio",x:1,f:"(Kas + Setara kas) / Utang lancar",v:[["Kas dan setara kas","Uang tunai, saldo bank, dan surat berharga yang bisa dicairkan segera"],["Utang lancar","Kewajiban yang jatuh tempo dalam satu tahun"]],r:"Ukuran likuiditas paling ketat: mampukah utang lancar dibayar dengan kas saja, tanpa menagih piutang atau menjual persediaan?",w:"Terlalu tinggi berarti dana menganggur yang mengorbankan profitabilitas. Perusahaan dengan siklus kas cepat bisa sehat walau cash ratio rendah.",dir:"hi",cut:[.1,.2,.4,.8],fm:"x",fn:y=>y.cash/y.cl,sub:y=>`${$(y.cash)} / ${$(y.cl)}`},
{id:"der",k:"leverage",n:"Debt-to-equity ratio (DER)",f:"Total utang / Ekuitas pemegang saham",v:[["Total utang","Utang lancar + utang jangka panjang"],["Ekuitas","Modal milik pemegang saham"]],r:"Berapa rupiah utang untuk tiap rupiah modal pemilik. Kreditor menyukai rasio rendah karena ekuitas yang tebal menjadi bantalan saat rugi.",w:"Wajar berbeda antar industri: perusahaan dengan arus kas stabil (seperti utilitas listrik) biasanya menanggung rasio lebih tinggi daripada perusahaan dengan arus kas fluktuatif. Saham preferen kadang dihitung sebagai utang.",dir:"lo",cut:[2,1.5,1,.5],fm:"x",fn:y=>(y.cl+y.ltd)/y.eq,sub:y=>`(${$(y.cl)} + ${$(y.ltd)}) / ${$(y.eq)}`},
{id:"dta",k:"leverage",n:"Debt-to-assets ratio (DAR)",f:"Total utang / Total aset",v:[["Total utang","Utang lancar + utang jangka panjang"],["Total aset","Seluruh aset perusahaan"]],r:"Porsi aset yang dibiayai dengan uang pinjaman. Makin tinggi, makin besar risiko keuangan.",w:"Pasangan debt-to-equity: keduanya melihat proporsi pendanaan kreditor dari sudut berbeda. Bisa pula dihitung dengan nilai pasar, bukan hanya nilai buku.",dir:"lo",cut:[.8,.6,.5,.3],fm:"%",fn:y=>(y.cl+y.ltd)/y.ta,sub:y=>`(${$(y.cl)} + ${$(y.ltd)}) / ${$(y.ta)}`},
{id:"er",k:"leverage",n:"Equity ratio",x:1,f:"Ekuitas pemegang saham / Total aset",v:[["Ekuitas","Modal milik pemegang saham"],["Total aset","Seluruh aset perusahaan"]],r:"Porsi aset yang dibiayai modal pemilik; kebalikan dari debt-to-assets. Bila seluruh pendanaan berasal dari utang dan ekuitas, jumlah keduanya 100%.",w:"Makin tinggi, makin tebal bantalan bagi kreditor. Namun ekuitas yang terlalu dominan berarti perusahaan tidak memanfaatkan utang, yang bunganya mengurangi pajak.",dir:"hi",cut:[.2,.4,.5,.7],fm:"%",fn:y=>y.eq/y.ta,sub:y=>`${$(y.eq)} / ${$(y.ta)}`},
{id:"ltc",k:"leverage",n:"Long-term debt to total capitalization",f:"Utang jangka panjang / (Utang jangka panjang + Ekuitas)",v:[["Utang jangka panjang","Utang yang jatuh tempo lebih dari setahun"],["Total kapitalisasi","Utang jangka panjang + ekuitas (pendanaan jangka panjang)"]],r:"Peran utang jangka panjang dalam struktur modal jangka panjang.",w:"Tidak memasukkan utang lancar, jadi cocok untuk menilai struktur modal permanen, tetapi tidak menangkap tekanan dari utang jangka pendek.",dir:"lo",cut:[.6,.5,.4,.2],fm:"%",fn:y=>y.ltd/(y.ltd+y.eq),sub:y=>`${$(y.ltd)} / (${$(y.ltd)} + ${$(y.eq)})`},
{id:"icr",k:"coverage",n:"Interest coverage ratio (ICR)",f:"EBIT / Beban bunga",v:[["EBIT","Laba sebelum bunga dan pajak"],["Beban bunga","Bunga utang pada periode itu"]],r:"Berapa kali laba operasi menutup bunga. Makin tinggi, makin kecil peluang gagal bayar bunga.",w:"Bunga sebenarnya dibayar dari kas, bukan dari laba, jadi lengkapi dengan analisis arus kas. Ukuran yang lebih realistis adalah fixed-charge coverage (memasukkan cicilan pokok, dividen preferen, sewa); tidak dihitung di lab ini karena butuh data tambahan.",dir:"hi",cut:[1.5,2.5,4,8],fm:"x",fn:y=>y.ebit/y.int,sub:y=>`${$(y.ebit)} / ${$(y.int)}`},
{id:"rt",k:"aktivitas",n:"Receivable turnover (RT)",f:"Penjualan kredit tahunan / Piutang",v:[["Penjualan kredit","Penjualan tahunan secara kredit (lab ini menganggap seluruh penjualan kredit)"],["Piutang","Saldo piutang usaha"]],r:"Berapa kali piutang berputar menjadi kas dalam setahun. Makin tinggi, makin cepat tertagih.",w:"Jika data penjualan kredit tidak ada, dipakai total penjualan. Saldo akhir tahun bisa menyesatkan bila penjualan musiman atau tumbuh cepat; rata-rata saldo lebih tepat.",nr:1,nw:"dinilai lewat versi hari (RTD) yang lebih mudah dibandingkan dengan syarat kredit.",fm:"x",fn:y=>D(y).rt,sub:y=>`${$(y.sales)} / ${$(y.ar)}`},
{id:"rtd",k:"aktivitas",n:"Receivable turnover in days (RTD)",f:"365 / RT",v:[["365","Jumlah hari dalam setahun"],["RT","Receivable turnover"]],r:"Rata-rata hari piutang tertagih (average collection period).",w:"Bandingkan dengan syarat kredit perusahaan sendiri dan median industri. Syarat 30 hari dengan RTD 60 hari berarti ada masalah penagihan atau kualitas piutang.",dir:"lo",cut:[90,60,45,30],fm:"h",fn:y=>D(y).rtd,sub:y=>`365 / ${q(D(y).rt)}`},
{id:"it",k:"aktivitas",n:"Inventory turnover (IT)",f:"Harga pokok penjualan / Persediaan",v:[["Harga pokok penjualan (HPP)","Biaya barang yang terjual dalam periode"],["Persediaan","Saldo persediaan"]],r:"Berapa kali persediaan terjual dalam setahun. Memberi petunjuk likuiditas persediaan dan kecenderungan menimbun.",w:"Turnover rendah bisa berarti persediaan menumpuk, usang, atau nilai bukunya melebihi nilai wajar. Jika begitu, likuiditas sebenarnya lebih rendah daripada yang ditunjukkan current ratio.",nr:1,nw:"dinilai lewat versi hari (ITD).",fm:"x",fn:y=>D(y).it,sub:y=>`${$(y.cogs)} / ${$(y.inv)}`},
{id:"itd",k:"aktivitas",n:"Inventory turnover in days (ITD)",f:"365 / IT",v:[["365","Jumlah hari dalam setahun"],["IT","Inventory turnover"]],r:"Rata-rata hari persediaan tersimpan sebelum terjual dan menjadi piutang.",w:"Patokan sangat bergantung industri (makanan segar berbeda jauh dari mesin berat). Pakai median industri sebagai pembanding utama.",dir:"lo",cut:[180,120,90,60],fm:"h",fn:y=>D(y).itd,sub:y=>`365 / ${q(D(y).it)}`},
{id:"ptd",k:"aktivitas",n:"Payable turnover in days (PTD)",f:"Utang usaha x 365 / HPP",v:[["Utang usaha","Saldo utang kepada pemasok"],["HPP","Dipakai sebagai pendekatan; idealnya pembelian kredit"]],r:"Rata-rata hari perusahaan membayar pemasoknya.",w:"Angka sangat panjang bisa berarti perusahaan menunda bayar, yang dapat merusak hubungan pemasok dan reputasi kredit.",nr:1,nw:"tidak ada patokan universal; dibaca bersama syarat kredit pemasok.",fm:"h",fn:y=>D(y).ptd,sub:y=>`${$(y.ap)} x 365 / ${$(y.cogs)}`},
{id:"tato",k:"aktivitas",n:"Total asset turnover",f:"Penjualan bersih / Total aset",v:[["Penjualan bersih","Penjualan setelah retur dan potongan"],["Total aset","Seluruh aset perusahaan"]],r:"Efisiensi seluruh aset dalam menghasilkan penjualan. Disebut juga capital turnover.",w:"Sangat bergantung industri: ritel dan grosir berputar jauh lebih cepat daripada industri padat modal.",dir:"hi",cut:[.5,.8,1.2,2],fm:"x",fn:y=>y.sales/y.ta,sub:y=>`${$(y.sales)} / ${$(y.ta)}`},
{id:"oc",k:"aktivitas",n:"Operating cycle",f:"ITD + RTD",v:[["ITD","Hari persediaan tersimpan"],["RTD","Hari menagih piutang"]],r:"Lama dari komitmen kas untuk pembelian sampai piutang hasil penjualan tertagih. Siklus pendek menandakan pengelolaan piutang dan persediaan yang efektif, sekaligus memperkuat likuiditas.",w:"Siklus yang panjang adalah tanda bahaya piutang atau persediaan berlebih, dan membuat likuiditas sebenarnya lebih lemah dari yang terlihat.",dir:"lo",cut:[240,180,120,80],fm:"h",fn:y=>D(y).oc,sub:y=>`${q(D(y).itd)} + ${q(D(y).rtd)}`},
{id:"cc",k:"aktivitas",n:"Cash cycle",f:"Operating cycle - PTD",v:[["Operating cycle","ITD + RTD"],["PTD","Hari membayar utang usaha"]],r:"Lama dari uang kas benar-benar keluar untuk pembelian sampai kas dari penjualan diterima.",w:"Hati-hati: siklus kas pendek bisa dicapai dengan tidak membayar tagihan tepat waktu (keputusan pendanaan yang buruk). Operating cycle memberi sinyal lebih jernih. Hanya perusahaan dengan persediaan JIT, penagihan ketat, dan daya tawar kuat yang bisa negatif secara sehat.",nr:1,nw:"gabungan keputusan operasi dan pendanaan sehingga mudah menyesatkan.",fm:"h",fn:y=>D(y).oc-D(y).ptd,sub:y=>`${q(D(y).oc)} - ${q(D(y).ptd)}`},
{id:"gm",k:"profitabilitas",n:"Gross profit margin",f:"(Penjualan bersih - HPP) / Penjualan bersih",v:[["Penjualan bersih","Penjualan setelah retur dan potongan"],["HPP","Harga pokok penjualan"]],r:"Laba setelah biaya produksi. Mencerminkan efisiensi produksi dan cara menetapkan harga.",w:"Berbeda jauh antar industri; bandingkan hanya dengan perusahaan sejenis.",dir:"hi",cut:[.1,.2,.3,.45],fm:"%",fn:y=>(y.sales-y.cogs)/y.sales,sub:y=>`(${$(y.sales)} - ${$(y.cogs)}) / ${$(y.sales)}`},
{id:"om",k:"profitabilitas",n:"Operating margin",x:1,f:"EBIT / Penjualan bersih",v:[["EBIT","Laba sebelum bunga dan pajak"]],r:"Laba operasi per rupiah penjualan, sebelum pengaruh bunga dan pajak.",w:"Rasio umum yang tidak ada di daftar buku; dimasukkan karena EBIT sudah dipakai di coverage.",dir:"hi",cut:[0,.05,.1,.18],fm:"%",fn:y=>y.ebit/y.sales,sub:y=>`${$(y.ebit)} / ${$(y.sales)}`},
{id:"nm",k:"profitabilitas",n:"Net profit margin",f:"Laba bersih setelah pajak / Penjualan bersih",v:[["Laba bersih","Laba setelah bunga dan pajak"]],r:"Laba bersih tiap rupiah penjualan.",w:"Margin kecil tidak selalu buruk bila perputaran asetnya tinggi (lihat ROA).",dir:"hi",cut:[0,.03,.07,.12],fm:"%",fn:y=>y.ni/y.sales,sub:y=>`${$(y.ni)} / ${$(y.sales)}`},
{id:"roa",k:"profitabilitas",n:"Return on assets / investment (ROA)",f:"Laba bersih / Total aset   =   Net profit margin x Total asset turnover",v:[["Laba bersih","Laba setelah pajak"],["Total aset","Seluruh aset"]],r:"Efektivitas seluruh aset menghasilkan laba; disebut juga earning power.",w:"Dua perusahaan dengan margin sangat berbeda bisa punya ROA sama bila perputaran asetnya berbeda (contoh buku: toko grosir margin 2% dengan perputaran 10 kali setara 20%).",dir:"hi",cut:[0,.03,.06,.1],fm:"%",fn:y=>y.ni/y.ta,sub:y=>`${$(y.ni)} / ${$(y.ta)}`},
{id:"roe",k:"profitabilitas",n:"Return on equity (ROE)",f:"Laba bersih / Ekuitas pemegang saham",v:[["Ekuitas","Nilai buku modal pemegang saham"]],r:"Return bagi pemegang saham atas nilai buku investasinya.",w:"ROE tinggi bisa berasal dari utang yang besar (equity multiplier tinggi), bukan operasi yang bagus. Periksa dengan Du Pont.",dir:"hi",cut:[0,.06,.12,.18],fm:"%",fn:y=>y.ni/y.eq,sub:y=>`${$(y.ni)} / ${$(y.eq)}`},
{id:"eps",k:"pasar",n:"Earnings per share (EPS)",x:1,f:"(Laba bersih - Dividen preferen) / Jumlah saham biasa beredar",v:[["Laba bersih","Laba setelah pajak"],["Dividen preferen","Hak pemegang saham preferen; di lab ini dianggap nol"],["Jumlah saham biasa","Saham beredar (miliar lembar)"]],r:"Laba yang menjadi hak tiap lembar saham biasa.",w:"Angka bergantung pada jumlah saham, sehingga tidak bisa dibandingkan antar perusahaan. Stock split atau penerbitan saham baru mengubah EPS tanpa mengubah kinerja; menerbitkan saham baru juga bisa menurunkan EPS.",nr:1,nw:"tergantung jumlah saham; baca tren dari tahun ke tahun.",fm:"rp",fn:y=>y.ni/y.sh,sub:y=>`${$(y.ni)} / ${$(y.sh)}`},
{id:"bvps",k:"pasar",n:"Book value per share (BVPS)",x:1,f:"Ekuitas pemegang saham biasa / Jumlah saham biasa beredar",v:[["Ekuitas pemegang saham biasa","Total ekuitas dikurangi ekuitas preferen (di lab ini seluruh ekuitas)"],["Jumlah saham biasa","Saham beredar (miliar lembar)"]],r:"Nilai buku ekuitas yang melekat pada tiap lembar saham.",w:"Nilai buku adalah angka akuntansi historis, bukan nilai wajar. Aset tak berwujud dan inflasi membuatnya menyimpang dari nilai pasar.",nr:1,nw:"nilai absolut bergantung jumlah saham; dipakai sebagai pembanding harga lewat PBV.",fm:"rp",fn:y=>y.eq/y.sh,sub:y=>`${$(y.eq)} / ${$(y.sh)}`},
{id:"per",k:"pasar",n:"Price to earnings ratio (PER)",x:1,f:"Harga per saham / EPS",v:[["Harga per saham","Harga pasar saham (Rp per lembar)"],["EPS","Earnings per share"]],r:"Berapa rupiah yang dibayar investor untuk tiap rupiah laba. PER tinggi berarti pasar menaruh ekspektasi pertumbuhan tinggi, atau harganya mahal.",w:"Tidak bermakna bila EPS negatif (ditampilkan tak terdefinisi). PER rendah belum tentu murah, bisa karena prospek buruk. Bandingkan dengan PER industri dan PER historis perusahaan sendiri.",nr:1,nw:"ukuran harga relatif, bukan kinerja; tinggi atau rendah tergantung industri dan prospek.",fm:"x",fn:y=>{const e=y.ni/y.sh;return e>0?y.px/e:NaN},sub:y=>`${$(y.px)} / ${$(y.ni/y.sh)}`},
{id:"pbv",k:"pasar",n:"Price to book value (PBV)",x:1,f:"Harga per saham / BVPS",v:[["Harga per saham","Harga pasar saham (Rp per lembar)"],["BVPS","Book value per share"]],r:"Harga pasar dibanding nilai buku per saham. Di bawah 1 berarti pasar menghargai perusahaan lebih rendah daripada nilai bukunya.",w:"PBV rendah bisa berarti saham murah, bisa juga perusahaan bermasalah (ROE rendah atau rugi). PBV tinggi lazim pada perusahaan dengan ROE tinggi atau aset tak berwujud besar.",nr:1,nw:"ukuran harga relatif; baca bersama ROE.",fm:"x",fn:y=>y.px/(y.eq/y.sh),sub:y=>`${$(y.px)} / ${$(y.eq/y.sh)}`},
{id:"dy",k:"pasar",n:"Dividend yield",x:2,f:"Dividen per saham (DPS) / Harga per saham",v:[["DPS","Dividen tunai per lembar yang dibayar pada tahun itu"],["Harga per saham","Harga pasar saham (Rp per lembar)"]],r:"Imbal hasil tunai dari dividen terhadap harga saham. Ini komponen D1/P0 pada rumus return saham di Bab 4; komponen lainnya adalah capital gains yield.",w:"Yield tinggi bisa muncul karena harga saham jatuh, bukan karena dividen royal. Periksa kemampuan membayar (laba dan arus kas). Dividen hanya sebagian dari total return.",nr:1,nw:"tergantung kebijakan dividen; yield tinggi tidak otomatis baik.",fm:"%",fn:y=>y.dps/y.px,sub:y=>`${$(y.dps)} / ${$(y.px)}`},
{id:"dp",k:"profitabilitas",n:"Du Pont (penguraian ROE)",f:"ROE = Net profit margin x Total asset turnover x Equity multiplier",v:[["Net profit margin","Laba bersih / Penjualan"],["Total asset turnover","Penjualan / Total aset"],["Equity multiplier","Total aset / Ekuitas (tingkat leverage)"]],r:"Memecah ROE menjadi tiga sumber: margin, efisiensi aset, dan leverage.",w:"Dipakai untuk menjelaskan mengapa ROE suatu perusahaan lebih tinggi atau rendah dari industri.",nr:1,nw:"ini alat penguraian, bukan ukuran yang punya patokan sendiri.",fm:"%",fn:y=>y.ni/y.sales*y.sales/y.ta*y.ta/y.eq,sub:y=>`${q(y.ni/y.sales)} x ${q(y.sales/y.ta)} x ${q(y.ta/y.eq)}`}
];
const FL=[["#","Laporan laba rugi"],["sales","Penjualan bersih"],["cogs","Harga pokok penjualan (HPP)"],["ebit","EBIT (laba operasi)"],["int","Beban bunga"],["ni","Laba bersih"],["#","Neraca"],["cash","Kas dan setara kas"],["ar","Piutang usaha"],["inv","Persediaan"],["ca","Aktiva lancar"],["ta","Total aset"],["ap","Utang usaha"],["cl","Utang lancar"],["ltd","Utang jangka panjang"],["eq","Ekuitas pemegang saham"],["#","Data saham"],["sh","Saham biasa beredar (miliar lembar)"],["px","Harga saham akhir tahun (Rp)"],["dps","Dividen per saham (Rp)"]];
const RD=[
{n:"PT Sinar Pangan Sejahtera",c:"produsen makanan yang makin efisien: margin naik, piutang dan persediaan makin cepat berputar, utang turun.",y:["2023","2024","2025"],d:{sales:[8000,8800,9600],cogs:[5600,6000,6400],ebit:[800,950,1100],int:[100,100,110],ni:[490,595,693],ar:[900,880,880],inv:[1000,950,900],ca:[2800,3000,3300],ta:[6000,6400,6800],ap:[700,700,720],cl:[1400,1450,1500],ltd:[1500,1400,1300],eq:[3100,3550,4000],cash:[500,650,900],sh:[.5,.5,.5],px:[9000,11500,15500],dps:[300,420,540]}},
{n:"PT Mega Logam Perkasa",c:"produsen logam yang memburuk: penjualan turun, margin menipis, piutang dan persediaan menumpuk, utang membengkak, rugi di 2025.",y:["2023","2024","2025"],d:{sales:[9000,8500,7600],cogs:[7000,6900,6500],ebit:[700,400,150],int:[250,300,330],ni:[315,70,-130],ar:[1100,1300,1500],inv:[1500,1900,2300],ca:[3300,3600,3900],ta:[6500,6800,6900],ap:[800,1000,1300],cl:[1800,2400,3000],ltd:[2000,2400,2700],eq:[2700,2000,1200],cash:[300,200,60],sh:[.4,.4,.4],px:[7000,4000,2500],dps:[200,50,0]}}];
const chip=l=>`<span class="chip l${l}">${LV[l]}</span>`;
const ptab=r=>r.nr?`<p class="use">Tidak diberi penilaian: ${r.nw}</p>`:`<p><b>Parameter</b> (pedoman umum)</p><div class="tw"><table class="dt pt"><tr>${LV.map((l,i)=>`<td>${chip(i)}</td>`).join('')}</tr><tr>${rng(r).map(t=>`<td>${t}</td>`).join('')}</tr></table></div>`;
const rcard=r=>`<div class="fc"><b>${r.n}</b>${r.x?` <small>(${r.x==2?'konsep Bab 4, di sini dihitung dengan dividen tahun berjalan':'tambahan, tidak ada di daftar rasio Bab 6'})</small>`:''}<code>${r.f}</code><dl>${r.v.map(x=>`<dt>${x[0]}</dt><dd>${x[1]}</dd>`).join('')}</dl><p><b>Artinya.</b> ${r.r}</p>${ptab(r)}<p><b>Perlu diwaspadai.</b> ${r.w}</p></div>`;
const rhome=()=>`<section class="page"><h2>Buku Rasio Keuangan</h2><p class="lead">Semua rasio Bab 6 plus rasio nilai pasar di satu tempat: rumus, arti tiap variabel, cara membaca, dan parameter penilaian. Setiap kelompok punya lab dengan data perusahaan dummy 3 tahun.</p><h3>Cara memakai rasio dengan benar</h3><ul><li>Satu rasio tidak cukup. Baca beberapa rasio bersama, misalnya current ratio dengan quick ratio, atau ROE dengan Du Pont.</li><li>Bandingkan dengan dua hal: tren perusahaan sendiri dan median industri sejenis. Buku selalu menilai rasio dengan cara ini.</li><li>Bila ada angka yang menyimpang, tugas analis adalah mencari sebabnya, bukan langsung menyimpulkan baik atau buruk.</li><li>Rasio neraca memakai saldo satu titik waktu. Saat penjualan musiman atau tumbuh cepat, saldo rata-rata lebih tepat.</li><li><b>Parameter Sangat Buruk sampai Sangat Baik di sini adalah pedoman umum</b> dari praktik analisis, bukan standar baku dan bukan angka dari buku. Industri yang berbeda punya patokan berbeda.</li></ul><h3>Enam kelompok rasio</h3><div class="cards">${RK.map(k=>`<a href="#/rasio/${k.id}"><b>${k.n}</b><br><small>${k.q}</small></a>`).join('')}</div><p><a class="btn" href="#/lab/r-semua">Dashboard semua rasio</a></p></section>`;
const rcat=id=>{const k=RK.find(x=>x.id==id);if(!k)return rhome();const i=RK.indexOf(k),b=`<a class="btn" href="#/lab/r-${id}">Buka lab ${k.n}</a>`;return `<section class="page"><p><a href="#/rasio">Buku Rasio</a></p><h2>${k.n}</h2><p class="lead">${k.q}</p><p>${k.d}</p><p>${b}</p>${RS.filter(r=>r.k==id).map(rcard).join('')}<p>${b}</p><p class="note">Parameter adalah pedoman umum, bukan standar baku. Selalu bandingkan dengan industri dan tren.</p><p>${i>0?`<a href="#/rasio/${RK[i-1].id}">Sebelumnya: ${RK[i-1].n}</a> &nbsp; `:''}${i<RK.length-1?`<a href="#/rasio/${RK[i+1].id}">Berikutnya: ${RK[i+1].n}</a>`:''}</p></section>`};
const rshelf=()=>`<div class="shelf"><span class="plate">Referensi</span><div class="books"><a class="spine p5" style="height:270px" href="#/rasio" aria-label="Buku Rasio Keuangan"><span>Buku Rasio Keuangan</span></a></div></div>`;
const rlab=id=>{const ks=id=='semua'?RK:RK.filter(k=>k.id==id);if(!ks.length)return labs();const y=RD[0].y;return `<section class="page"><p><a href="#/lab">Semua laboratorium</a>${id!='semua'?` | <a href="#/rasio/${id}">Teori di Buku Rasio</a>`:''}</p><h2>${id=='semua'?'Dashboard semua rasio':'Lab rasio '+ks[0].n}</h2><p class="lead">Data keuangan dummy 3 tahun. Angka di tabel bisa kamu ubah; rasio dan penilaiannya ikut berubah.</p><p>${RD.map((c,i)=>`<button class="btn" onclick="useR(${i})">${c.n}</button>`).join('')}</p><p id="rdesc" class="note"></p><h3>Data keuangan (Rp miliar, kecuali data saham)</h3><div class="tw"><table class="dt rt" id="rtab"><tr><th>Pos</th>${y.map(t=>`<th>${t}</th>`).join('')}</tr>${FL.map(f=>f[0]=='#'?`<tr><th colspan="4">${f[1]}</th></tr>`:`<tr><td>${f[1]}</td>${[0,1,2].map(j=>`<td><input type="number" step="any" data-f="${f[0]}" data-y="${j}" aria-label="${f[1]} ${y[j]}"></td>`).join('')}</tr>`).join('')}</table></div><p id="rbal" class="note"></p><h3>Hasil rasio dan penilaian</h3><div class="tw" id="rres"></div><p id="rsum"></p><p class="note">Penilaian memakai parameter pedoman umum (lihat Buku Rasio), bukan standar baku.</p><h3>Langkah hitung</h3><label>Tahun: <select id="ry"><option value="0">${y[0]}</option><option value="1">${y[1]}</option><option value="2" selected>${y[2]}</option></select></label><div id="rstep"></div></section>`};
let RID='semua';
function useR(i){const c=RD[i];document.querySelectorAll('#rtab input').forEach(e=>e.value=c.d[e.dataset.f][+e.dataset.y]);document.getElementById('rdesc').textContent=c.n+': '+c.c;rcalc()}
function initR(id){RID=id;document.querySelectorAll('#rtab input').forEach(e=>e.addEventListener('input',rcalc));document.getElementById('ry').addEventListener('change',rcalc);useR(0)}
function rcalc(){const ks=RID=='semua'?RK:RK.filter(k=>k.id==RID),ys=RD[0].y,Y=[0,1,2].map(j=>{const o={};document.querySelectorAll('#rtab [data-y="'+j+'"]').forEach(e=>o[e.dataset.f]=+e.value);return o});
const bad=Y.map((y,j)=>Math.abs(y.ta-(y.cl+y.ltd+y.eq))>.5?ys[j]:null).filter(Boolean),bad2=Y.map((y,j)=>y.cash+y.ar+y.inv>y.ca+.5?ys[j]:null).filter(Boolean);
document.getElementById('rbal').textContent=(bad.length?'Peringatan: neraca tahun '+bad.join(', ')+' belum seimbang (total aset harus sama dengan utang lancar + utang jangka panjang + ekuitas). ':'')+(bad2.length?'Peringatan: pada tahun '+bad2.join(', ')+' kas + piutang + persediaan melebihi aktiva lancar.':'')||'Data konsisten: neraca seimbang dan komponen aktiva lancar tidak melebihi totalnya.';
let h=`<table class="dt rt"><tr><th>Rasio</th>${ys.map(t=>`<th>${t}</th>`).join('')}<th>Tren</th></tr>`,c=[0,0,0];
ks.forEach(k=>{h+=`<tr><th colspan="5">${k.n}</th></tr>`;RS.filter(r=>r.k==k.id).forEach(r=>{const vs=Y.map(y=>r.fn(y)),ls=vs.map(v=>rate(v,r));let tr='-';if(ls[0]>=0&&ls[2]>=0){const d=vs[2]-vs[0];tr=Math.abs(d)<1e-9?'Stabil':((r.dir=='hi')==(d>0)?'<span class="up">&#9650; Membaik</span>':'<span class="dn">&#9660; Memburuk</span>')}else if(isFinite(vs[0])&&isFinite(vs[2])){const d=vs[2]-vs[0];tr=Math.abs(d)<1e-9?'Stabil':d>0?'&#9650; Naik':'&#9660; Turun'}if(ls[2]>=0)c[ls[2]>=3?0:ls[2]==2?1:2]++;h+=`<tr><td>${r.n}<br><small>${r.f}</small></td>${vs.map((v,j)=>`<td>${fv(v,r.fm)}${ls[j]>=0?'<br>'+chip(ls[j]):''}</td>`).join('')}<td>${tr}</td></tr>`})});
document.getElementById('rres').innerHTML=h+'</table>';
document.getElementById('rsum').innerHTML=c[0]+c[1]+c[2]?`<b>Ringkasan ${ys[2]}:</b> dari ${c[0]+c[1]+c[2]} rasio yang dinilai, ${c[0]} berstatus Baik atau Sangat Baik, ${c[1]} Cukup, dan ${c[2]} Buruk atau Sangat Buruk.`:'Kelompok ini tidak diberi penilaian Baik atau Buruk. Baca sebagai perbandingan dengan industri dan dengan tahun-tahun sebelumnya; panah Naik dan Turun hanya menunjukkan arah, bukan kebaikan.';
const j=+document.getElementById('ry').value,y=Y[j];
document.getElementById('rstep').innerHTML=ks.map(k=>RS.filter(r=>r.k==k.id).map(r=>{const v=r.fn(y),l=rate(v,r);return `<div class="stp"><b>${r.n}</b> ${l>=0?chip(l):''}<code>${r.f}</code><div class="sub">${r.sub(y)}</div><div class="rs">= ${fv(v,r.fm)}</div></div>`}).join('')).join('');}
