// Sumber tunggal semua rumus. b=bab, n=nama, f=rumus, v=[simbol, arti], u=kapan dipakai.
// Catatan: i, y, k, g ditulis sebagai desimal (8% = 0,08) kecuali disebut lain.
const R=[
// Bab 2
{b:2,n:"Tarif pajak rata-rata",f:"Tarif rata-rata = Total pajak / Laba kena pajak",v:[["Total pajak","Pajak yang benar-benar dibayar"],["Laba kena pajak","Laba setelah pengurang pajak yang diizinkan"]],u:"Beda dengan tarif marjinal, yaitu tarif untuk tambahan laba berikutnya."},
// Bab 3
{b:3,n:"Bunga sederhana",f:"Bunga = P x i x n",v:[["P","Pokok pinjaman atau tabungan"],["i","Bunga per tahun"],["n","Jumlah tahun"]],u:"Bunga hanya dari pokok, tidak ada bunga-atas-bunga."},
{b:3,n:"Future value (jumlah tunggal)",f:"FV = PV x (1 + i)^n",v:[["FV","Nilai di masa depan"],["PV","Nilai sekarang"],["i","Bunga per periode"],["n","Jumlah periode"]],u:"Berapa nilai uang sekarang di masa depan."},
{b:3,n:"Present value (jumlah tunggal)",f:"PV = FV / (1 + i)^n",v:[["PV","Nilai sekarang"],["FV","Jumlah yang akan diterima di masa depan"],["i","Bunga atau tingkat diskonto per periode"],["n","Jumlah periode sampai uang diterima"]],u:"Berapa nilai uang masa depan jika dinilai hari ini."},
{b:3,n:"Future value anuitas biasa",f:"FVA = PMT x [((1 + i)^n - 1) / i]",v:[["FVA","Nilai masa depan seluruh pembayaran"],["PMT","Pembayaran sama besar tiap periode, di akhir periode"],["i","Bunga per periode"],["n","Jumlah pembayaran"]],u:"Menabung rutin: berapa total di akhir?"},
{b:3,n:"Present value anuitas biasa",f:"PVA = PMT x [(1 - (1 + i)^-n) / i]",v:[["PVA","Nilai sekarang seluruh pembayaran"],["PMT","Pembayaran sama besar tiap periode, di akhir periode"],["i","Bunga atau tingkat diskonto per periode"],["n","Jumlah pembayaran"]],u:"Berapa nilai sekarang dari cicilan atau pensiun bulanan."},
{b:3,n:"Annuity due",f:"FVAD = FVA x (1 + i)   dan   PVAD = PVA x (1 + i)",v:[["FVAD, PVAD","Nilai masa depan dan nilai sekarang annuity due"],["FVA, PVA","Nilai anuitas biasa dengan PMT, i, n yang sama"],["(1 + i)","Pengali karena tiap pembayaran terjadi satu periode lebih awal"]],u:"Pembayaran di awal periode, misalnya sewa dibayar di muka."},
{b:3,n:"Majemuk lebih dari sekali setahun",f:"FV = PV x (1 + i/m)^(m x n)",v:[["i","Bunga nominal per tahun"],["m","Frekuensi majemuk per tahun (semesteran 2, kuartalan 4, bulanan 12)"],["i/m","Bunga per periode majemuk"],["m x n","Total periode majemuk"]],u:"Bunga dihitung lebih sering dari setahun."},
{b:3,n:"Effective annual rate (EAR)",f:"EAR = (1 + i/m)^m - 1",v:[["EAR","Bunga tahunan efektif"],["i","Bunga nominal per tahun"],["m","Frekuensi majemuk per tahun"]],u:"Membandingkan tawaran bunga dengan frekuensi majemuk berbeda."},
{b:3,n:"Majemuk kontinu",f:"FV = PV x e^(i x n)",v:[["e","Konstanta Euler, sekitar 2,71828"],["i","Bunga nominal per tahun"],["n","Jumlah tahun"]],u:"Batas dari majemuk yang sangat sering."},
{b:3,n:"Rule of 72",f:"Tahun menggandakan uang = 72 / i",v:[["i","Bunga per tahun dalam persen (6% ditulis 6, bukan 0,06)"]],u:"Perkiraan cepat, bukan hitungan eksak."},
{b:3,n:"Cicilan amortisasi",f:"PMT = Pinjaman / PVIFA,   PVIFA = [1 - (1 + i)^-n] / i",v:[["PMT","Cicilan tetap per periode"],["Pinjaman","Pokok pinjaman awal"],["PVIFA","Faktor nilai sekarang anuitas"],["i","Bunga per periode"],["n","Jumlah cicilan"]],u:"Menghitung cicilan kredit."},
{b:3,n:"Bunga dan pokok tiap cicilan",f:"Bunga(t) = Sisa(t-1) x i;  Pokok(t) = PMT - Bunga(t);  Sisa(t) = Sisa(t-1) - Pokok(t)",v:[["Sisa(t-1)","Sisa pinjaman sebelum cicilan ke-t"],["Bunga(t)","Porsi bunga di cicilan ke-t"],["Pokok(t)","Porsi pelunasan pokok di cicilan ke-t"]],u:"Membuat tabel amortisasi. Porsi pokok membesar dari waktu ke waktu."},
// Bab 4
{b:4,n:"Nilai obligasi berkupon",f:"P = I x [(1 - (1 + y)^-n) / y] + F / (1 + y)^n",v:[["P","Harga atau nilai intrinsik obligasi"],["I","Bunga kupon per periode = nominal x tingkat kupon"],["F","Nilai nominal, dibayar saat jatuh tempo"],["y","Required return (yield) per periode"],["n","Jumlah periode sampai jatuh tempo"]],u:"Kupon di atas yield menghasilkan premium; di bawah yield menghasilkan diskon."},
{b:4,n:"Obligasi zero-coupon",f:"P = F / (1 + y)^n",v:[["P","Harga obligasi"],["F","Nilai nominal"],["y","Yield per periode"],["n","Periode sampai jatuh tempo"]],u:"Tidak ada kupon, hanya pelunasan pokok."},
{b:4,n:"Obligasi perpetual",f:"P = I / y",v:[["P","Harga obligasi"],["I","Bunga tetap per periode, selamanya"],["y","Required return per periode"]],u:"Obligasi tanpa jatuh tempo."},
{b:4,n:"Saham preferen",f:"V = D / k",v:[["V","Nilai intrinsik saham preferen"],["D","Dividen preferen tetap per tahun"],["k","Required return investor"]],u:"Dividen tetap selamanya, jadi sama seperti perpetuitas."},
{b:4,n:"Saham biasa, dividen tumbuh konstan",f:"V = D1 / (ke - g)",v:[["V","Nilai intrinsik saham"],["D1","Dividen tahun depan = D0 x (1 + g)"],["D0","Dividen terakhir yang sudah dibayar"],["ke","Required return pemegang saham biasa"],["g","Pertumbuhan dividen per tahun, konstan"]],u:"Syarat: ke harus lebih besar dari g."},
{b:4,n:"Saham biasa tanpa pertumbuhan",f:"V = D1 / ke",v:[["V","Nilai intrinsik saham"],["D1","Dividen tahun depan (sama setiap tahun)"],["ke","Required return"]],u:"Kasus khusus saat g = 0."},
{b:4,n:"Yield saham biasa",f:"ke = D1 / P0 + g",v:[["ke","Return yang diharapkan dari saham"],["D1 / P0","Dividend yield"],["P0","Harga pasar saham sekarang"],["g","Capital gains yield (pertumbuhan harga)"]],u:"Return saham berasal dari dividen dan kenaikan harga."},
{b:4,n:"Yield to maturity (YTM)",f:"P0 = I x [(1 - (1 + YTM)^-n) / YTM] + F / (1 + YTM)^n   (cari YTM)",v:[["P0","Harga pasar obligasi sekarang"],["YTM","Return jika dibeli di P0 dan ditahan sampai jatuh tempo (IRR obligasi)"],["I, F, n","Kupon per periode, nominal, sisa periode"]],u:"Dicari dengan coba-coba, tabel, atau kalkulator keuangan."},
// Bab 5
{b:5,n:"Holding period return",f:"R = (P1 - P0 + CF) / P0",v:[["R","Return selama periode kepemilikan"],["P1","Harga akhir periode"],["P0","Harga awal periode"],["CF","Kas yang diterima (dividen atau bunga)"]],u:"Return satu periode dari suatu investasi."},
{b:5,n:"Expected return",f:"E(R) = Σ pj x Rj",v:[["E(R)","Return yang diharapkan"],["pj","Peluang terjadinya kondisi j (total 100%)"],["Rj","Return jika kondisi j terjadi"],["Σ","Jumlahkan untuk semua kondisi"]],u:"Rata-rata return tertimbang peluang."},
{b:5,n:"Varians",f:"σ² = Σ pj x (Rj - E(R))²",v:[["σ²","Varians return"],["pj, Rj","Peluang dan return kondisi j"],["E(R)","Expected return"]],u:"Rata-rata kuadrat selisih dari nilai harapan."},
{b:5,n:"Standar deviasi",f:"σ = akar(σ²)",v:[["σ","Standar deviasi, ukuran risiko (sebaran return)"],["σ²","Varians"]],u:"Makin besar σ, makin berisiko."},
{b:5,n:"Coefficient of variation (CV)",f:"CV = σ / E(R)",v:[["CV","Risiko per unit return"],["σ","Standar deviasi"],["E(R)","Expected return"]],u:"Membandingkan investasi yang skala return-nya berbeda."},
{b:5,n:"Return portofolio",f:"Rp = Σ Wj x Rj",v:[["Rp","Expected return portofolio"],["Wj","Bobot: proporsi dana di sekuritas j (total 100%)"],["Rj","Expected return sekuritas j"]],u:"Rata-rata tertimbang return tiap sekuritas."},
{b:5,n:"Kovarians dan korelasi",f:"Cov(A,B) = ρAB x σA x σB",v:[["Cov(A,B)","Kovarians: seberapa kompak A dan B bergerak"],["ρAB","Koefisien korelasi, dari -1 sampai +1"],["σA, σB","Standar deviasi saham A dan B"]],u:"Diversifikasi mengurangi risiko selama ρ kurang dari +1."},
{b:5,n:"Risiko portofolio dua aset",f:"σp = akar(WA²σA² + WB²σB² + 2 WA WB Cov(A,B))",v:[["σp","Standar deviasi portofolio"],["WA, WB","Bobot aset A dan B"],["σA, σB","Standar deviasi A dan B"],["Cov(A,B)","Kovarians A dan B"]],u:"Makin rendah kovarians, makin kecil risiko portofolio."},
{b:5,n:"CAPM (garis SML)",f:"k = Rf + β x (Rm - Rf)",v:[["k","Required return saham"],["Rf","Return bebas risiko (misal surat utang pemerintah)"],["β","Beta: ukuran risiko sistematis saham"],["Rm","Return pasar yang diharapkan"],["Rm - Rf","Premi risiko pasar"]],u:"Menentukan return minimum yang pantas untuk risiko sistematis."},
{b:5,n:"Beta",f:"β = Cov(Rj, Rm) / σm²",v:[["β","Kemiringan characteristic line saham"],["Cov(Rj, Rm)","Kovarians return saham j dan return pasar"],["σm²","Varians return pasar"]],u:"β di atas 1: lebih agresif dari pasar. Di bawah 1: lebih defensif."},
// Bab 6
{b:6,n:"Current ratio",f:"Aktiva lancar / Utang lancar",v:[["Aktiva lancar","Kas, surat berharga, piutang, persediaan"],["Utang lancar","Kewajiban jatuh tempo dalam setahun"]],u:"Kemampuan memenuhi utang jangka pendek."},
{b:6,n:"Quick (acid-test) ratio",f:"(Aktiva lancar - Persediaan) / Utang lancar",v:[["Persediaan","Dikeluarkan karena paling lambat dicairkan"]],u:"Versi likuiditas yang lebih ketat."},
{b:6,n:"Debt to equity",f:"Total utang / Ekuitas pemegang saham",v:[["Total utang","Utang lancar + utang jangka panjang"],["Ekuitas","Modal pemilik"]],u:"Seberapa besar utang dibanding modal sendiri."},
{b:6,n:"Debt to total assets",f:"Total utang / Total aset",v:[["Total aset","Seluruh aset perusahaan"]],u:"Porsi aset yang dibiayai utang."},
{b:6,n:"Interest coverage",f:"EBIT / Beban bunga",v:[["EBIT","Laba sebelum bunga dan pajak"],["Beban bunga","Bunga utang per periode"]],u:"Berapa kali laba operasi menutup bunga."},
{b:6,n:"Receivable turnover dan hari penagihan",f:"RT = Penjualan kredit / Piutang;   RTD = 365 / RT",v:[["RT","Perputaran piutang (kali per tahun)"],["Penjualan kredit","Penjualan tahunan secara kredit"],["RTD","Rata-rata hari menagih piutang"]],u:"Kualitas dan kecepatan penagihan piutang."},
{b:6,n:"Inventory turnover",f:"IT = Harga pokok penjualan / Persediaan;   ITD = 365 / IT",v:[["IT","Perputaran persediaan"],["Harga pokok penjualan","Biaya barang yang terjual dalam periode"],["ITD","Rata-rata hari persediaan tersimpan"]],u:"Efisiensi pengelolaan persediaan."},
{b:6,n:"Total asset turnover",f:"Penjualan / Total aset",v:[["Penjualan","Penjualan bersih periode"]],u:"Seberapa efektif aset menghasilkan penjualan."},
{b:6,n:"Net profit margin",f:"Laba bersih / Penjualan",v:[["Laba bersih","Laba setelah bunga dan pajak"]],u:"Laba dari setiap rupiah penjualan."},
{b:6,n:"ROA (return on investment)",f:"Laba bersih / Total aset",v:[["Laba bersih","Laba setelah pajak"],["Total aset","Seluruh aset"]],u:"Daya hasilkan laba dari seluruh aset."},
{b:6,n:"ROE",f:"Laba bersih / Ekuitas",v:[["Ekuitas","Modal pemilik"]],u:"Return bagi pemegang saham."},
{b:6,n:"Du Pont",f:"ROE = (Laba bersih / Penjualan) x (Penjualan / Total aset) x (Total aset / Ekuitas)",v:[["Laba bersih / Penjualan","Net profit margin"],["Penjualan / Total aset","Perputaran aset"],["Total aset / Ekuitas","Equity multiplier (tingkat leverage)"]],u:"Memecah ROE menjadi margin, efisiensi aset, dan leverage."},
{b:6,n:"Operating cycle dan cash cycle",f:"Operating cycle = ITD + RTD;   Cash cycle = Operating cycle - PTD",v:[["ITD","Hari persediaan tersimpan"],["RTD","Hari menagih piutang"],["PTD","Rata-rata hari membayar utang usaha"]],u:"Lamanya dana tertahan, dari pembelian sampai kas diterima."},
{b:6,n:"Long-term debt to total capitalization",f:"Utang jangka panjang / (Utang jangka panjang + Ekuitas)",v:[["Utang jangka panjang","Utang jatuh tempo lebih dari setahun"],["Total kapitalisasi","Utang jangka panjang + ekuitas"]],u:"Peran utang jangka panjang dalam pendanaan jangka panjang."},
{b:6,n:"Gross profit margin",f:"(Penjualan bersih - HPP) / Penjualan bersih",v:[["HPP","Harga pokok penjualan"],["Penjualan bersih","Penjualan setelah retur dan potongan"]],u:"Efisiensi produksi dan penetapan harga."},
{b:6,n:"Payable turnover in days (PTD)",f:"PTD = Utang usaha x 365 / HPP",v:[["Utang usaha","Saldo utang ke pemasok"],["HPP","Pendekatan untuk pembelian kredit"]],u:"Dipakai untuk menghitung cash cycle."},
{b:6,n:"Cash ratio (tambahan)",f:"(Kas + Setara kas) / Utang lancar",v:[["Kas dan setara kas","Tunai, saldo bank, surat berharga yang segera cair"],["Utang lancar","Kewajiban jatuh tempo dalam setahun"]],u:"Likuiditas paling ketat, tanpa piutang dan persediaan."},
{b:6,n:"Equity ratio (tambahan)",f:"Ekuitas pemegang saham / Total aset",v:[["Ekuitas","Modal milik pemegang saham"],["Total aset","Seluruh aset"]],u:"Porsi aset yang dibiayai modal pemilik; kebalikan debt-to-assets."},
{b:6,n:"Earnings per share, EPS (tambahan)",f:"EPS = (Laba bersih - Dividen preferen) / Jumlah saham biasa beredar",v:[["Laba bersih","Laba setelah pajak"],["Dividen preferen","Hak pemegang saham preferen"],["Saham biasa beredar","Jumlah lembar saham biasa"]],u:"Laba per lembar saham."},
{b:6,n:"Book value per share, BVPS (tambahan)",f:"BVPS = Ekuitas pemegang saham biasa / Jumlah saham biasa beredar",v:[["Ekuitas biasa","Ekuitas dikurangi ekuitas preferen"],["Saham biasa beredar","Jumlah lembar saham biasa"]],u:"Nilai buku per lembar saham."},
{b:6,n:"Price to earnings ratio, PER (tambahan)",f:"PER = Harga per saham / EPS",v:[["Harga per saham","Harga pasar per lembar"],["EPS","Earnings per share"]],u:"Berapa kali laba per saham yang dibayar investor. Tidak bermakna bila EPS negatif."},
{b:6,n:"Price to book value, PBV (tambahan)",f:"PBV = Harga per saham / BVPS",v:[["Harga per saham","Harga pasar per lembar"],["BVPS","Book value per share"]],u:"Di bawah 1: harga pasar lebih rendah dari nilai buku per saham."},
{b:6,n:"Dividend yield",f:"Dividend yield = DPS / Harga per saham",v:[["DPS","Dividen tunai per lembar"],["Harga per saham","Harga pasar per lembar"]],u:"Komponen D1/P0 pada yield saham Bab 4."},
// Bab 7
{b:7,n:"Saldo kas di cash budget",f:"Saldo akhir = Saldo awal + Penerimaan - Pengeluaran",v:[["Saldo awal","Kas di awal periode"],["Penerimaan","Kas masuk periode itu"],["Pengeluaran","Kas keluar periode itu"]],u:"Memperkirakan kebutuhan pendanaan jangka pendek."},
{b:7,n:"Aturan sumber dan penggunaan dana",f:"Sumber = aset turun atau utang/ekuitas naik;  Penggunaan = aset naik atau utang/ekuitas turun",v:[["Aset","Termasuk kas"],["Utang/ekuitas","Kewajiban dan modal pemilik"]],u:"Menyusun laporan sources and uses of funds dari dua neraca."},
// Bab 8
{b:8,n:"Net dan gross working capital",f:"NWC = Aktiva lancar - Utang lancar;   Gross WC = Aktiva lancar",v:[["NWC","Net working capital (versi akuntan)"],["Gross WC","Dalam keuangan, modal kerja berarti aktiva lancar"]],u:"Dasar pembahasan modal kerja."},
// Bab 10
{b:10,n:"Economic order quantity (EOQ)",f:"EOQ = akar(2 x S x O / C)",v:[["S","Pemakaian per tahun (unit)"],["O","Biaya per pesanan"],["C","Biaya simpan per unit per tahun"]],u:"Ukuran pesanan yang meminimalkan total biaya."},
{b:10,n:"Total biaya persediaan",f:"TC = (S / Q) x O + (Q / 2) x C",v:[["Q","Ukuran pesanan"],["S / Q","Jumlah pesanan per tahun"],["Q / 2","Rata-rata persediaan di gudang"]],u:"Membandingkan ukuran pesanan, minimum tepat di EOQ."},
{b:10,n:"Order point",f:"Order point = Pemakaian per hari x Lead time (+ Safety stock)",v:[["Lead time","Hari dari pemesanan sampai barang tiba"],["Safety stock","Cadangan untuk lonjakan permintaan atau keterlambatan"]],u:"Kapan harus memesan ulang sebesar EOQ."},
// Bab 11
{b:11,n:"Biaya tidak mengambil diskon tunai",f:"Biaya = d / (1 - d) x 365 / (Hari bayar - Hari diskon)",v:[["d","Persentase diskon (2% = 0,02)"],["Hari bayar","Hari jatuh tempo (net)"],["Hari diskon","Batas hari untuk mendapat diskon"]],u:"Menilai apakah lebih baik pinjam dulu demi mengambil diskon."},
{b:11,n:"Biaya efektif dengan compensating balance",f:"Biaya efektif = Bunga / (Pinjaman - Compensating balance)",v:[["Bunga","Bunga yang dibayar"],["Compensating balance","Saldo yang wajib ditahan di bank"],["Pinjaman - CB","Dana yang benar-benar bisa dipakai"]],u:"Bentuk sederhana; compensating balance menaikkan biaya efektif."},
// Bab 12
{b:12,n:"Initial cash outflow",f:"Biaya aset baru + Biaya kapitalisasi + Δ NWC - Hasil jual aset lama ± Pajak jual aset lama",v:[["Biaya kapitalisasi","Pemasangan, pengiriman; masuk dasar depresiasi"],["Δ NWC","Perubahan net working capital karena proyek"],["Aset lama","Hanya pada keputusan penggantian"]],u:"Arus kas keluar di awal proyek (Tabel 12.3)."},
{b:12,n:"Arus kas inkremental interim",f:"ΔCF = (ΔPendapatan - ΔBiaya operasi tanpa depresiasi - ΔDepresiasi) x (1 - T) + ΔDepresiasi",v:[["ΔCF","Arus kas bersih tambahan per periode"],["T","Tarif pajak"],["ΔDepresiasi","Perubahan depresiasi pajak; dikurangkan lalu ditambahkan kembali karena bukan kas"]],u:"Arus kas operasi tahun-tahun tengah proyek (Tabel 12.4)."},
{b:12,n:"Arus kas inkremental tahun terakhir",f:"CF akhir = ΔCF interim + Nilai sisa - Pajak atas penjualan ± Pemulihan NWC",v:[["Nilai sisa","Hasil penjualan atau pembongkaran aset baru"],["Pemulihan NWC","Modal kerja yang dilepas saat proyek berakhir"]],u:"Arus kas periode terakhir (Tabel 12.5)."},
// Bab 13
{b:13,n:"Payback period",f:"Payback = tahun penuh sebelum kembali + (Sisa investasi / CF tahun kembali)",v:[["Sisa investasi","Investasi yang belum tertutup di awal tahun kembali modal"],["CF tahun kembali","Arus kas pada tahun itu"]],u:"Ukuran likuiditas kasar; mengabaikan nilai waktu uang."},
{b:13,n:"Net present value (NPV)",f:"NPV = Σ CFt / (1 + k)^t - ICO",v:[["CFt","Arus kas bersih tahun ke-t"],["k","Required return proyek"],["ICO","Initial cash outflow (investasi awal)"],["t","Tahun ke-1 sampai n"]],u:"Terima proyek jika NPV lebih dari atau sama dengan nol."},
{b:13,n:"Profitability index (PI)",f:"PI = Σ [CFt / (1 + k)^t] / ICO",v:[["Σ CFt / (1+k)^t","Nilai sekarang seluruh arus kas masuk"],["ICO","Investasi awal"]],u:"Terima jika PI lebih dari atau sama dengan 1. Berguna saat capital rationing."},
{b:13,n:"Internal rate of return (IRR)",f:"Σ CFt / (1 + IRR)^t = ICO   (cari IRR)",v:[["IRR","Diskonto yang membuat NPV = 0"],["CFt, ICO","Arus kas dan investasi awal"]],u:"Terima jika IRR lebih dari atau sama dengan required return."},
// Bab 14
{b:14,n:"Expected NPV dan sebaran proyek",f:"E(NPV) = Σ pj x NPVj;   σ = akar(Σ pj x (NPVj - E(NPV))²)",v:[["pj","Peluang skenario j"],["NPVj","NPV pada skenario j"],["σ","Standar deviasi NPV (risiko proyek)"]],u:"Dari probability tree atau simulasi."},
{b:14,n:"CV proyek",f:"CV = σ / E(NPV)",v:[["σ","Standar deviasi sebaran"],["E(NPV)","Nilai harapan"]],u:"Risiko relatif; bandingkan proyek berbeda skala."},
{b:14,n:"Peluang NPV di bawah nilai tertentu (distribusi normal)",f:"z = (X - E(NPV)) / σ",v:[["X","Nilai yang ditanyakan, misalnya NPV = 0"],["z","Jarak X dari nilai harapan dalam satuan σ"],["Tabel V","Tabel distribusi normal di akhir buku mengubah z menjadi peluang"]],u:"Menjawab: berapa peluang proyek rugi?"}
];
